import { pgTable, index, bigserial, timestamp, text, boolean, integer, primaryKey, date } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const rssHealthStatus = pgTable("rss_health_status", {
	id: bigserial({ mode: "bigint" }).primaryKey().notNull(),
	ranAt: timestamp("ran_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	runner: text().default('api_news').notNull(),
	outletId: text("outlet_id").notNull(),
	source: text().notNull(),
	method: text().notNull(),
	attempted: boolean().default(false).notNull(),
	circuitOpen: boolean("circuit_open").default(false).notNull(),
	ok: boolean().default(false).notNull(),
	statusCode: integer("status_code"),
	parsedCount: integer("parsed_count").default(0).notNull(),
	parsedLimit: integer("parsed_limit"),
	sampleCapped: boolean("sample_capped").default(false).notNull(),
	recent24H: integer().default(0).notNull(),
	error: text(),
	country: text().default('Global').notNull(),
	fetchedCount: integer("fetched_count").default(0).notNull(),
	missingTitleCount: integer("missing_title_count").default(0).notNull(),
	missingSummaryCount: integer("missing_summary_count").default(0).notNull(),
	missingPublishedAtCount: integer("missing_published_at_count").default(0).notNull(),
	missingLinkCount: integer("missing_link_count").default(0).notNull(),
}, (table) => [
	index("idx_rss_health_status_country").using("btree", table.country.asc().nullsLast().op("text_ops")),
	index("idx_rss_health_status_outlet_id").using("btree", table.outletId.asc().nullsLast().op("text_ops")),
	index("idx_rss_health_status_ran_at").using("btree", table.ranAt.desc().nullsFirst().op("timestamptz_ops")),
	index("idx_rss_health_status_runner_ran_at").using("btree", table.runner.asc().nullsLast().op("text_ops"), table.ranAt.desc().nullsFirst().op("text_ops")),
	index("idx_rss_health_status_source").using("btree", table.source.asc().nullsLast().op("text_ops")),
]);

export const newsArticles = pgTable("news_articles", {
	externalId: text("external_id").primaryKey().notNull(),
	stableId: text("stable_id"),
	publicationDatetime: timestamp("publication_datetime", { withTimezone: true, mode: 'string' }).notNull(),
	titleOriginal: text("title_original").notNull(),
	snippetOriginal: text("snippet_original"),
	country: text(),
	sourceCountry: text("source_country"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	url: text().notNull(),
	source: text().notNull(),
	language: text(),
	section: text(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_news_articles_country").using("btree", table.country.asc().nullsLast().op("text_ops")),
	index("idx_news_articles_created_at").using("btree", table.createdAt.desc().nullsFirst().op("timestamptz_ops")),
	index("idx_news_articles_section").using("btree", table.section.asc().nullsLast().op("text_ops")),
	index("idx_news_articles_source_country").using("btree", table.sourceCountry.asc().nullsLast().op("text_ops")),
	index("idx_news_articles_source").using("btree", table.source.asc().nullsLast().op("text_ops")),
	index("idx_news_articles_stable_id").using("btree", table.stableId.asc().nullsLast().op("text_ops")),
	index("idx_news_articles_updated_at").using("btree", table.updatedAt.desc().nullsFirst().op("timestamptz_ops")),
	index("idx_news_articles_url").using("btree", table.url.asc().nullsLast().op("text_ops")),
]);

export const ingestFeedWatermarks = pgTable("ingest_feed_watermarks_v2", {
	outletId: text("outlet_id").notNull(),
	source: text().notNull(),
	country: text().default('Global').notNull(),
	method: text().notNull(),
	lastPublicationAt: timestamp("last_publication_at", { withTimezone: true, mode: 'string' }),
	lastFetchedAt: timestamp("last_fetched_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_ingest_feed_watermarks_v2_country").using("btree", table.country.asc().nullsLast().op("text_ops")),
	index("idx_ingest_feed_watermarks_v2_source").using("btree", table.source.asc().nullsLast().op("text_ops")),
	primaryKey({ columns: [table.outletId, table.method], name: "ingest_feed_watermarks_v2_pkey"}),
]);

export const ingestOpsHourly = pgTable("ingest_ops_hourly", {
	hourBucket: timestamp("hour_bucket", { withTimezone: true, mode: 'string' }).notNull(),
	runner: text().default('worker').notNull(),
	outletId: text("outlet_id").notNull(),
	source: text().notNull(),
	country: text().default('Global').notNull(),
	method: text().notNull(),
	attemptedRuns: integer("attempted_runs").default(0).notNull(),
	successfulRuns: integer("successful_runs").default(0).notNull(),
	failedRuns: integer("failed_runs").default(0).notNull(),
	fetchedCount: integer("fetched_count").default(0).notNull(),
	validCount: integer("valid_count").default(0).notNull(),
	missingTitleCount: integer("missing_title_count").default(0).notNull(),
	missingSummaryCount: integer("missing_summary_count").default(0).notNull(),
	missingPublishedAtCount: integer("missing_published_at_count").default(0).notNull(),
	missingLinkCount: integer("missing_link_count").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_ingest_ops_hourly_country").using("btree", table.country.asc().nullsLast().op("text_ops")),
	index("idx_ingest_ops_hourly_hour").using("btree", table.hourBucket.desc().nullsFirst().op("timestamptz_ops")),
	index("idx_ingest_ops_hourly_source").using("btree", table.source.asc().nullsLast().op("text_ops")),
	primaryKey({ columns: [table.hourBucket, table.runner, table.outletId, table.method], name: "ingest_ops_hourly_pkey"}),
]);

export const ingestOpsDaily = pgTable("ingest_ops_daily", {
	dayBucket: date("day_bucket").notNull(),
	runner: text().default('worker').notNull(),
	outletId: text("outlet_id").notNull(),
	source: text().notNull(),
	country: text().default('Global').notNull(),
	method: text().notNull(),
	attemptedRuns: integer("attempted_runs").default(0).notNull(),
	successfulRuns: integer("successful_runs").default(0).notNull(),
	failedRuns: integer("failed_runs").default(0).notNull(),
	fetchedCount: integer("fetched_count").default(0).notNull(),
	validCount: integer("valid_count").default(0).notNull(),
	missingTitleCount: integer("missing_title_count").default(0).notNull(),
	missingSummaryCount: integer("missing_summary_count").default(0).notNull(),
	missingPublishedAtCount: integer("missing_published_at_count").default(0).notNull(),
	missingLinkCount: integer("missing_link_count").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_ingest_ops_daily_country").using("btree", table.country.asc().nullsLast().op("text_ops")),
	index("idx_ingest_ops_daily_day").using("btree", table.dayBucket.desc().nullsFirst().op("date_ops")),
	index("idx_ingest_ops_daily_source").using("btree", table.source.asc().nullsLast().op("text_ops")),
	primaryKey({ columns: [table.dayBucket, table.runner, table.outletId, table.method], name: "ingest_ops_daily_pkey"}),
]);

export const countryBenchmarkHourly = pgTable("country_benchmark_hourly", {
	hourBucket: timestamp("hour_bucket", { withTimezone: true, mode: 'string' }).notNull(),
	country: text().notNull(),
	windowStart: timestamp("window_start", { withTimezone: true, mode: 'string' }).notNull(),
	windowEnd: timestamp("window_end", { withTimezone: true, mode: 'string' }).notNull(),
	metricVersion: text("metric_version").default('v1').notNull(),
	atlasVersion: text("atlas_version"),
	publishedLast24H: integer("published_last_24h").default(0).notNull(),
	freshLast24H: integer("fresh_last_24h").default(0).notNull(),
	lateLast24H: integer("late_last_24h").default(0).notNull(),
	insertedLast24H: integer("inserted_last_24h").default(0).notNull(),
	insertedLast1H: integer("inserted_last_1h").default(0).notNull(),
	activeSourcesLast24H: integer("active_sources_last_24h").default(0).notNull(),
	activeSourcesLast1H: integer("active_sources_last_1h").default(0).notNull(),
	topSourceShareBps: integer("top_source_share_bps").default(0).notNull(),
	top5SourceShareBps: integer("top_5_source_share_bps").default(0).notNull(),
	top10SourceShareBps: integer("top_10_source_share_bps").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_country_benchmark_hourly_country").using("btree", table.country.asc().nullsLast().op("text_ops")),
	index("idx_country_benchmark_hourly_hour").using("btree", table.hourBucket.desc().nullsFirst().op("timestamptz_ops")),
	primaryKey({ columns: [table.hourBucket, table.country, table.metricVersion], name: "country_benchmark_hourly_pkey"}),
]);

export const countryBenchmarkDaily = pgTable("country_benchmark_daily", {
	dayBucket: date("day_bucket").notNull(),
	country: text().notNull(),
	windowStart: timestamp("window_start", { withTimezone: true, mode: 'string' }).notNull(),
	windowEnd: timestamp("window_end", { withTimezone: true, mode: 'string' }).notNull(),
	metricVersion: text("metric_version").default('v1').notNull(),
	atlasVersion: text("atlas_version"),
	publishedCount: integer("published_count").default(0).notNull(),
	freshCount: integer("fresh_count").default(0).notNull(),
	lateCount: integer("late_count").default(0).notNull(),
	insertedCount: integer("inserted_count").default(0).notNull(),
	activeSourcesCount: integer("active_sources_count").default(0).notNull(),
	topSourceShareBps: integer("top_source_share_bps").default(0).notNull(),
	top5SourceShareBps: integer("top_5_source_share_bps").default(0).notNull(),
	top10SourceShareBps: integer("top_10_source_share_bps").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_country_benchmark_daily_country").using("btree", table.country.asc().nullsLast().op("text_ops")),
	index("idx_country_benchmark_daily_day").using("btree", table.dayBucket.desc().nullsFirst().op("date_ops")),
	primaryKey({ columns: [table.dayBucket, table.country, table.metricVersion], name: "country_benchmark_daily_pkey"}),
]);

export const countryBenchmarkSourceDaily = pgTable("country_benchmark_source_daily", {
	dayBucket: date("day_bucket").notNull(),
	country: text().notNull(),
	source: text().notNull(),
	windowStart: timestamp("window_start", { withTimezone: true, mode: 'string' }).notNull(),
	windowEnd: timestamp("window_end", { withTimezone: true, mode: 'string' }).notNull(),
	metricVersion: text("metric_version").default('v1').notNull(),
	atlasVersion: text("atlas_version"),
	publishedCount: integer("published_count").default(0).notNull(),
	freshCount: integer("fresh_count").default(0).notNull(),
	lateCount: integer("late_count").default(0).notNull(),
	insertedCount: integer("inserted_count").default(0).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_country_benchmark_source_daily_country").using("btree", table.country.asc().nullsLast().op("text_ops")),
	index("idx_country_benchmark_source_daily_day").using("btree", table.dayBucket.desc().nullsFirst().op("date_ops")),
	index("idx_country_benchmark_source_daily_source").using("btree", table.source.asc().nullsLast().op("text_ops")),
	primaryKey({ columns: [table.dayBucket, table.country, table.source, table.metricVersion], name: "country_benchmark_source_daily_pkey"}),
]);

export const countryBenchmarkExternalDaily = pgTable("country_benchmark_external_daily", {
	dayBucket: date("day_bucket").notNull(),
	country: text().notNull(),
	provider: text().notNull(),
	metricName: text("metric_name").default('article_count').notNull(),
	metricVersion: text("metric_version").default('v1').notNull(),
	referenceValue: integer("reference_value").default(0).notNull(),
	referenceUrl: text("reference_url"),
	notes: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	index("idx_country_benchmark_external_daily_country").using("btree", table.country.asc().nullsLast().op("text_ops")),
	index("idx_country_benchmark_external_daily_day").using("btree", table.dayBucket.desc().nullsFirst().op("date_ops")),
	index("idx_country_benchmark_external_daily_provider").using("btree", table.provider.asc().nullsLast().op("text_ops")),
	primaryKey({ columns: [table.dayBucket, table.country, table.provider, table.metricName, table.metricVersion], name: "country_benchmark_external_daily_pkey"}),
]);
