import { readFileSync } from 'node:fs';
import path from 'node:path';
import { buildDisplaySourceName } from '@/lib/source-display';

export type PublisherHeadquartersRecord = {
  country: string;
  publisher: string;
  city: string;
  region: string;
  lat: number;
  lon: number;
  label: string;
};

export type ResolvedPublisherHeadquarters = {
  city: string;
  region: string;
  lat: number;
  lon: number;
  label: string;
};

function normalizePublisher(value: string): string {
  return buildDisplaySourceName(value || '').trim().toLowerCase();
}

export const PUBLISHER_HEADQUARTERS: PublisherHeadquartersRecord[] = [
  {
    country: 'Australia',
    publisher: 'Nine Entertainment',
    city: 'Sydney',
    region: 'North Sydney',
    lat: -33.8382,
    lon: 151.2082,
    label: 'Nine Entertainment HQ',
  },
  {
    country: 'Australia',
    publisher: 'News Corp Australia',
    city: 'Sydney',
    region: 'Surry Hills',
    lat: -33.885,
    lon: 151.2093,
    label: 'News Corp Australia HQ',
  },
  {
    country: 'Australia',
    publisher: 'Australian Community Media',
    city: 'Canberra',
    region: 'City West',
    lat: -35.2806,
    lon: 149.1289,
    label: 'Australian Community Media HQ',
  },
  {
    country: 'Australia',
    publisher: 'Australian Broadcasting Corporation',
    city: 'Sydney',
    region: 'Ultimo',
    lat: -33.8785,
    lon: 151.1993,
    label: 'ABC HQ',
  },
  {
    country: 'Australia',
    publisher: 'AAP',
    city: 'Sydney',
    region: 'Surry Hills',
    lat: -33.8859,
    lon: 151.2111,
    label: 'AAP HQ',
  },
  {
    country: 'Austria',
    publisher: 'Die Presse',
    city: 'Vienna',
    region: 'Landstrasse',
    lat: 48.195,
    lon: 16.392,
    label: 'Die Presse HQ',
  },
  {
    country: 'Austria',
    publisher: 'Kleine Zeitung',
    city: 'Graz',
    region: 'Graz',
    lat: 47.0707,
    lon: 15.4395,
    label: 'Kleine Zeitung HQ',
  },
  {
    country: 'Austria',
    publisher: 'PULS 24',
    city: 'Vienna',
    region: 'Landstrasse',
    lat: 48.1869,
    lon: 16.4101,
    label: 'PULS 24 HQ',
  },
  {
    country: 'Austria',
    publisher: 'Heute',
    city: 'Vienna',
    region: 'Innere Stadt',
    lat: 48.2025,
    lon: 16.3717,
    label: 'Heute HQ',
  },
  {
    country: 'Austria',
    publisher: 'Kurier',
    city: 'Vienna',
    region: 'Dobling',
    lat: 48.2509,
    lon: 16.366,
    label: 'Kurier HQ',
  },
  {
    country: 'Austria',
    publisher: 'ORF',
    city: 'Vienna',
    region: 'Hietzing',
    lat: 48.1846,
    lon: 16.2849,
    label: 'ORF HQ',
  },
  {
    country: 'Austria',
    publisher: 'VOL.AT',
    city: 'Schwarzach',
    region: 'Vorarlberg',
    lat: 47.4507,
    lon: 9.7624,
    label: 'VOL.AT HQ',
  },
  {
    country: 'Austria',
    publisher: 'profil',
    city: 'Vienna',
    region: 'Dobling',
    lat: 48.2509,
    lon: 16.366,
    label: 'profil HQ',
  },
  {
    country: 'Ireland',
    publisher: 'Mediahuis Ireland',
    city: 'Dublin',
    region: 'Dublin 1',
    lat: 53.3511,
    lon: -6.2521,
    label: 'Mediahuis Ireland HQ',
  },
  {
    country: 'Ireland',
    publisher: 'Reach',
    city: 'Dublin',
    region: 'Dublin 2',
    lat: 53.3348,
    lon: -6.2474,
    label: 'Reach Ireland HQ',
  },
  {
    country: 'Ireland',
    publisher: 'RTÉ',
    city: 'Dublin',
    region: 'Donnybrook',
    lat: 53.3197,
    lon: -6.2308,
    label: 'RTÉ HQ',
  },
  {
    country: 'Ireland',
    publisher: 'Journal Media',
    city: 'Dublin',
    region: 'Dublin 8',
    lat: 53.3391,
    lon: -6.2729,
    label: 'TheJournal.ie HQ',
  },
  {
    country: 'Ireland',
    publisher: 'The Irish Times',
    city: 'Dublin',
    region: 'Dublin 2',
    lat: 53.347,
    lon: -6.2572,
    label: 'The Irish Times HQ',
  },
  {
    country: 'Ireland',
    publisher: 'BreakingNews.ie',
    city: 'Dublin',
    region: 'Dublin 2',
    lat: 53.347,
    lon: -6.2572,
    label: 'BreakingNews.ie HQ',
  },
  {
    country: 'Ireland',
    publisher: 'DMG Media Ireland',
    city: 'Dublin',
    region: 'Dublin 4',
    lat: 53.3343,
    lon: -6.2367,
    label: 'Extra.ie HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'RTL Nieuws',
    city: 'Hilversum',
    region: 'Media Park',
    lat: 52.2288,
    lon: 5.174,
    label: 'RTL Nieuws HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'Tweakers',
    city: 'Amsterdam',
    region: 'Duivendrecht',
    lat: 52.3355,
    lon: 4.9194,
    label: 'Tweakers HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'BNNVARA',
    city: 'Hilversum',
    region: 'Media Park',
    lat: 52.2284,
    lon: 5.1728,
    label: 'BNNVARA HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'Omrop Fryslan',
    city: 'Leeuwarden',
    region: 'Camminghaburen',
    lat: 53.2104,
    lon: 5.8426,
    label: 'Omrop Fryslan HQ',
  },
  {
    country: 'Italy',
    publisher: 'ANSA',
    city: 'Rome',
    region: 'Rome',
    lat: 41.9028,
    lon: 12.4964,
    label: 'ANSA HQ',
  },
  {
    country: 'Italy',
    publisher: 'Corriere della Sera',
    city: 'Milan',
    region: 'Milan',
    lat: 45.4642,
    lon: 9.19,
    label: 'Corriere della Sera HQ',
  },
  {
    country: 'Italy',
    publisher: 'la Repubblica',
    city: 'Rome',
    region: 'Rome',
    lat: 41.9028,
    lon: 12.4964,
    label: 'la Repubblica HQ',
  },
  {
    country: 'Italy',
    publisher: 'La Stampa',
    city: 'Turin',
    region: 'Turin',
    lat: 45.0703,
    lon: 7.6869,
    label: 'La Stampa HQ',
  },
  {
    country: 'Italy',
    publisher: 'Il Sole 24 Ore',
    city: 'Milan',
    region: 'Milan',
    lat: 45.4642,
    lon: 9.19,
    label: 'Il Sole 24 Ore HQ',
  },
  {
    country: 'Italy',
    publisher: 'RaiNews',
    city: 'Rome',
    region: 'Rome',
    lat: 41.9028,
    lon: 12.4964,
    label: 'RaiNews HQ',
  },
  {
    country: 'Italy',
    publisher: 'TgCom24',
    city: 'Milan',
    region: 'Milan',
    lat: 45.4642,
    lon: 9.19,
    label: 'TgCom24 HQ',
  },
  {
    country: 'Italy',
    publisher: 'Adnkronos',
    city: 'Rome',
    region: 'Rome',
    lat: 41.9028,
    lon: 12.4964,
    label: 'Adnkronos HQ',
  },
  {
    country: 'Italy',
    publisher: 'AGI',
    city: 'Rome',
    region: 'Rome',
    lat: 41.9028,
    lon: 12.4964,
    label: 'AGI HQ',
  },
  {
    country: 'Italy',
    publisher: 'Il Messaggero',
    city: 'Rome',
    region: 'Rome',
    lat: 41.9028,
    lon: 12.4964,
    label: 'Il Messaggero HQ',
  },
  {
    country: 'Italy',
    publisher: 'Il Giornale',
    city: 'Milan',
    region: 'Milan',
    lat: 45.4642,
    lon: 9.19,
    label: 'Il Giornale HQ',
  },
  {
    country: 'Japan',
    publisher: 'NHK',
    city: 'Tokyo',
    region: 'Jinnan',
    lat: 35.6641,
    lon: 139.6987,
    label: 'NHK HQ',
  },
  {
    country: 'Japan',
    publisher: 'Mainichi Shimbun',
    city: 'Tokyo',
    region: 'Hitotsubashi',
    lat: 35.6913,
    lon: 139.7585,
    label: 'Mainichi Shimbun HQ',
  },
  {
    country: 'Japan',
    publisher: 'ITmedia',
    city: 'Tokyo',
    region: 'Kioicho',
    lat: 35.6817,
    lon: 139.7397,
    label: 'ITmedia HQ',
  },
  {
    country: 'Japan',
    publisher: 'Impress',
    city: 'Tokyo',
    region: 'Jimbocho',
    lat: 35.6952,
    lon: 139.7587,
    label: 'Impress HQ',
  },
  {
    country: 'Japan',
    publisher: 'PR TIMES',
    city: 'Tokyo',
    region: 'Akasaka',
    lat: 35.6727,
    lon: 139.7418,
    label: 'PR TIMES HQ',
  },
  {
    country: 'Japan',
    publisher: 'Toyo Keizai',
    city: 'Tokyo',
    region: 'Nihonbashi Hongokucho',
    lat: 35.6867,
    lon: 139.7727,
    label: 'Toyo Keizai HQ',
  },
  {
    country: 'Japan',
    publisher: 'J-CAST',
    city: 'Tokyo',
    region: 'Nibancho',
    lat: 35.6858,
    lon: 139.7368,
    label: 'J-CAST HQ',
  },
  {
    country: 'Russia',
    publisher: 'TASS',
    city: 'Moscow',
    region: 'Moscow',
    lat: 55.7558,
    lon: 37.6173,
    label: 'TASS HQ',
  },
  {
    country: 'Russia',
    publisher: 'RIA Novosti',
    city: 'Moscow',
    region: 'Moscow',
    lat: 55.7558,
    lon: 37.6173,
    label: 'RIA Novosti HQ',
  },
  {
    country: 'Russia',
    publisher: 'RT',
    city: 'Moscow',
    region: 'Moscow',
    lat: 55.7558,
    lon: 37.6173,
    label: 'RT HQ',
  },
  {
    country: 'Russia',
    publisher: 'Interfax',
    city: 'Moscow',
    region: 'Moscow',
    lat: 55.7558,
    lon: 37.6173,
    label: 'Interfax HQ',
  },
  {
    country: 'Russia',
    publisher: 'Kommersant',
    city: 'Moscow',
    region: 'Moscow',
    lat: 55.7558,
    lon: 37.6173,
    label: 'Kommersant HQ',
  },
  {
    country: 'Russia',
    publisher: 'RBC',
    city: 'Moscow',
    region: 'Moscow',
    lat: 55.7558,
    lon: 37.6173,
    label: 'RBC HQ',
  },
  {
    country: 'Russia',
    publisher: 'Vedomosti',
    city: 'Moscow',
    region: 'Moscow',
    lat: 55.7558,
    lon: 37.6173,
    label: 'Vedomosti HQ',
  },
  {
    country: 'Russia',
    publisher: 'Gazeta.ru',
    city: 'Moscow',
    region: 'Moscow',
    lat: 55.7558,
    lon: 37.6173,
    label: 'Gazeta.ru HQ',
  },
  {
    country: 'Russia',
    publisher: 'Lenta.ru',
    city: 'Moscow',
    region: 'Moscow',
    lat: 55.7558,
    lon: 37.6173,
    label: 'Lenta.ru HQ',
  },
  {
    country: 'Russia',
    publisher: 'Rossiyskaya Gazeta',
    city: 'Moscow',
    region: 'Moscow',
    lat: 55.7558,
    lon: 37.6173,
    label: 'Rossiyskaya Gazeta HQ',
  },
  {
    country: 'Russia',
    publisher: 'Expert.ru',
    city: 'Moscow',
    region: 'Moscow',
    lat: 55.7558,
    lon: 37.6173,
    label: 'Expert.ru HQ',
  },
  {
    country: 'Russia',
    publisher: 'Rambler',
    city: 'Moscow',
    region: 'Moscow',
    lat: 55.7558,
    lon: 37.6173,
    label: 'Rambler HQ',
  },
  {
    country: 'United States',
    publisher: 'Politico',
    city: 'Arlington',
    region: 'Rosslyn',
    lat: 38.895,
    lon: -77.0729,
    label: 'POLITICO HQ',
  },
  {
    country: 'United States',
    publisher: 'USA Today',
    city: 'McLean',
    region: 'Jones Branch',
    lat: 38.9252,
    lon: -77.2218,
    label: 'USA Today HQ',
  },
  {
    country: 'United States',
    publisher: 'CNBC',
    city: 'Englewood Cliffs',
    region: 'Sylvan Avenue',
    lat: 40.8841,
    lon: -73.9513,
    label: 'CNBC HQ',
  },
  {
    country: 'United States',
    publisher: 'Vox Media',
    city: 'Washington',
    region: 'K Street NW',
    lat: 38.9026,
    lon: -77.0429,
    label: 'Vox Media HQ',
  },
  {
    country: 'United States',
    publisher: 'TechCrunch',
    city: 'San Francisco',
    region: 'Financial District',
    lat: 37.7906,
    lon: -122.4012,
    label: 'TechCrunch HQ',
  },
  {
    country: 'United States',
    publisher: 'LA Times',
    city: 'El Segundo',
    region: 'Imperial Highway',
    lat: 33.9164,
    lon: -118.3767,
    label: 'Los Angeles Times HQ',
  },
  {
    country: 'Mexico',
    publisher: 'Azteca Noticias',
    city: 'Mexico City',
    region: 'Fuentes del Pedregal',
    lat: 19.2997,
    lon: -99.2089,
    label: 'TV Azteca HQ',
  },
  {
    country: 'Mexico',
    publisher: 'Excelsior',
    city: 'Mexico City',
    region: 'Benito Juarez',
    lat: 19.3571,
    lon: -99.1676,
    label: 'Excelsior HQ',
  },
  {
    country: 'Mexico',
    publisher: 'Grupo Milenio',
    city: 'Mexico City',
    region: 'Centro',
    lat: 19.4318,
    lon: -99.1386,
    label: 'Grupo Milenio HQ',
  },
  {
    country: 'Mexico',
    publisher: 'El Universal',
    city: 'Mexico City',
    region: 'Cuauhtemoc',
    lat: 19.4336,
    lon: -99.1501,
    label: 'El Universal HQ',
  },
  {
    country: 'Mexico',
    publisher: 'Reforma',
    city: 'Mexico City',
    region: 'Santa Cruz Atoyac',
    lat: 19.3655,
    lon: -99.1675,
    label: 'Reforma HQ',
  },
  {
    country: 'Mexico',
    publisher: 'El Economista',
    city: 'Mexico City',
    region: 'Jardines del Pedregal',
    lat: 19.3228,
    lon: -99.2136,
    label: 'El Economista HQ',
  },
  {
    country: 'Mexico',
    publisher: 'Proceso',
    city: 'Mexico City',
    region: 'Del Valle',
    lat: 19.3838,
    lon: -99.1692,
    label: 'Proceso HQ',
  },
  {
    country: 'Mexico',
    publisher: 'El Financiero',
    city: 'Mexico City',
    region: 'Santa Fe',
    lat: 19.3618,
    lon: -99.273,
    label: 'El Financiero HQ',
  },
  {
    country: 'Mexico',
    publisher: 'La Jornada',
    city: 'Mexico City',
    region: 'Santa Cruz Atoyac',
    lat: 19.3651,
    lon: -99.1642,
    label: 'La Jornada HQ',
  },
  {
    country: 'Dominican Republic',
    publisher: 'Acento',
    city: 'Santo Domingo',
    region: 'Santo Domingo',
    lat: 18.4861,
    lon: -69.9312,
    label: 'Acento HQ',
  },
  {
    country: 'Dominican Republic',
    publisher: 'AlMomento',
    city: 'Santo Domingo',
    region: 'Santo Domingo',
    lat: 18.4861,
    lon: -69.9312,
    label: 'AlMomento HQ',
  },
  {
    country: 'Dominican Republic',
    publisher: 'De Último Minuto',
    city: 'Santo Domingo',
    region: 'Santo Domingo',
    lat: 18.4861,
    lon: -69.9312,
    label: 'De Último Minuto HQ',
  },
  {
    country: 'Dominican Republic',
    publisher: 'Diario Libre',
    city: 'Santo Domingo',
    region: 'Santo Domingo',
    lat: 18.4861,
    lon: -69.9312,
    label: 'Diario Libre HQ',
  },
  {
    country: 'Dominican Republic',
    publisher: 'Listín Diario',
    city: 'Santo Domingo',
    region: 'Santo Domingo',
    lat: 18.4861,
    lon: -69.9312,
    label: 'Listín Diario HQ',
  },
  {
    country: 'Dominican Republic',
    publisher: 'Periódico Hoy',
    city: 'Santo Domingo',
    region: 'Santo Domingo',
    lat: 18.4861,
    lon: -69.9312,
    label: 'Periódico Hoy HQ',
  },
  {
    country: 'Dominican Republic',
    publisher: 'Z101 Digital',
    city: 'Santo Domingo',
    region: 'Santo Domingo',
    lat: 18.4861,
    lon: -69.9312,
    label: 'Z101 Digital HQ',
  },
  {
    country: 'Jordan',
    publisher: 'Al Mamlaka TV',
    city: 'Amman',
    region: 'Amman',
    lat: 31.9539,
    lon: 35.9106,
    label: 'Al Mamlaka TV HQ',
  },
  {
    country: 'Jordan',
    publisher: 'Al Rai',
    city: 'Amman',
    region: 'Amman',
    lat: 31.9539,
    lon: 35.9106,
    label: 'Al Rai HQ',
  },
  {
    country: 'Jordan',
    publisher: 'Al Wakeel News',
    city: 'Amman',
    region: 'Amman',
    lat: 31.9539,
    lon: 35.9106,
    label: 'Al Wakeel News HQ',
  },
  {
    country: 'Jordan',
    publisher: 'Ammon News',
    city: 'Amman',
    region: 'Amman',
    lat: 31.9539,
    lon: 35.9106,
    label: 'Ammon News HQ',
  },
  {
    country: 'Jordan',
    publisher: 'JFRA News',
    city: 'Amman',
    region: 'Amman',
    lat: 31.9539,
    lon: 35.9106,
    label: 'JFRA News HQ',
  },
  {
    country: 'Jordan',
    publisher: 'Jo24',
    city: 'Amman',
    region: 'Amman',
    lat: 31.9539,
    lon: 35.9106,
    label: 'Jo24 HQ',
  },
  {
    country: 'Jordan',
    publisher: 'Jordan News',
    city: 'Amman',
    region: 'Amman',
    lat: 31.9539,
    lon: 35.9106,
    label: 'Jordan News HQ',
  },
  {
    country: 'Jordan',
    publisher: 'Khaberni',
    city: 'Amman',
    region: 'Amman',
    lat: 31.9539,
    lon: 35.9106,
    label: 'Khaberni HQ',
  },
  {
    country: 'Jordan',
    publisher: 'Roya News',
    city: 'Amman',
    region: 'Amman',
    lat: 31.9539,
    lon: 35.9106,
    label: 'Roya News HQ',
  },
  {
    country: 'Jordan',
    publisher: 'Saraya',
    city: 'Amman',
    region: 'Amman',
    lat: 31.9539,
    lon: 35.9106,
    label: 'Saraya HQ',
  },
  {
    country: 'Jordan',
    publisher: 'Sawaleif',
    city: 'Amman',
    region: 'Amman',
    lat: 31.9539,
    lon: 35.9106,
    label: 'Sawaleif HQ',
  },
  {
    country: 'Jordan',
    publisher: 'WatanA News',
    city: 'Amman',
    region: 'Amman',
    lat: 31.9539,
    lon: 35.9106,
    label: 'WatanA News HQ',
  },
  {
    country: 'Kuwait',
    publisher: 'Alanba',
    city: 'Kuwait City',
    region: 'Kuwait City',
    lat: 29.3759,
    lon: 47.9774,
    label: 'Alanba HQ',
  },
  {
    country: 'Kuwait',
    publisher: 'Al Rai Media',
    city: 'Kuwait City',
    region: 'Kuwait City',
    lat: 29.3759,
    lon: 47.9774,
    label: 'Al Rai Media HQ',
  },
  {
    country: 'Kuwait',
    publisher: 'Al Seyassah',
    city: 'Kuwait City',
    region: 'Kuwait City',
    lat: 29.3759,
    lon: 47.9774,
    label: 'Al Seyassah HQ',
  },
  {
    country: 'Kuwait',
    publisher: 'Aljarida',
    city: 'Kuwait City',
    region: 'Kuwait City',
    lat: 29.3759,
    lon: 47.9774,
    label: 'Aljarida HQ',
  },
  {
    country: 'Kuwait',
    publisher: 'Arab Times',
    city: 'Kuwait City',
    region: 'Kuwait City',
    lat: 29.3759,
    lon: 47.9774,
    label: 'Arab Times HQ',
  },
  {
    country: 'Kuwait',
    publisher: 'Boursa Kuwait',
    city: 'Kuwait City',
    region: 'Kuwait City',
    lat: 29.3759,
    lon: 47.9774,
    label: 'Boursa Kuwait HQ',
  },
  {
    country: 'Kuwait',
    publisher: 'Kuwait News',
    city: 'Kuwait City',
    region: 'Kuwait City',
    lat: 29.3759,
    lon: 47.9774,
    label: 'Kuwait News HQ',
  },
  {
    country: 'Kuwait',
    publisher: 'Kuwait Times',
    city: 'Kuwait City',
    region: 'Kuwait City',
    lat: 29.3759,
    lon: 47.9774,
    label: 'Kuwait Times HQ',
  },
  {
    country: 'Kuwait',
    publisher: 'Times Kuwait',
    city: 'Kuwait City',
    region: 'Kuwait City',
    lat: 29.3759,
    lon: 47.9774,
    label: 'Times Kuwait HQ',
  },
  {
    country: 'Indonesia',
    publisher: 'MetroTV News',
    city: 'Jakarta',
    region: 'Kedoya',
    lat: -6.1644,
    lon: 106.763,
    label: 'MetroTV News HQ',
  },
  {
    country: 'Philippines',
    publisher: 'Rappler',
    city: 'Pasig',
    region: 'Julia Vargas',
    lat: 14.5843,
    lon: 121.0622,
    label: 'Rappler HQ',
  },
  {
    country: 'Philippines',
    publisher: 'Inquirer',
    city: 'Makati',
    region: 'La Paz',
    lat: 14.5577,
    lon: 121.0136,
    label: 'Inquirer HQ',
  },
  {
    country: 'Philippines',
    publisher: 'BusinessWorld',
    city: 'Quezon City',
    region: 'New Manila',
    lat: 14.6198,
    lon: 121.0437,
    label: 'BusinessWorld HQ',
  },
  {
    country: 'Philippines',
    publisher: 'Philstar',
    city: 'Taguig',
    region: 'Bonifacio Global City',
    lat: 14.5516,
    lon: 121.0498,
    label: 'Philstar HQ',
  },
  {
    country: 'Philippines',
    publisher: 'GMA Network',
    city: 'Quezon City',
    region: 'South Triangle',
    lat: 14.6346,
    lon: 121.0384,
    label: 'GMA Network HQ',
  },
  {
    country: 'Philippines',
    publisher: 'MindaNews',
    city: 'Davao City',
    region: 'Poblacion District',
    lat: 7.0707,
    lon: 125.6087,
    label: 'MindaNews HQ',
  },
  {
    country: 'Philippines',
    publisher: 'The Manila Times',
    city: 'Taguig',
    region: 'Bonifacio Global City',
    lat: 14.5487,
    lon: 121.0509,
    label: 'The Manila Times HQ',
  },
  {
    country: 'Philippines',
    publisher: 'Manila Bulletin',
    city: 'Manila',
    region: 'Intramuros',
    lat: 14.5906,
    lon: 120.9747,
    label: 'Manila Bulletin HQ',
  },
  {
    country: 'Philippines',
    publisher: 'SunStar',
    city: 'Cebu City',
    region: 'P. del Rosario',
    lat: 10.2973,
    lon: 123.9017,
    label: 'SunStar HQ',
  },
  {
    country: 'Philippines',
    publisher: 'InterAksyon',
    city: 'Taguig',
    region: 'Bonifacio Global City',
    lat: 14.5516,
    lon: 121.0498,
    label: 'InterAksyon HQ',
  },
  {
    country: 'Philippines',
    publisher: 'Daily Tribune',
    city: 'Makati',
    region: 'Bel-Air',
    lat: 14.5605,
    lon: 121.0244,
    label: 'Daily Tribune HQ',
  },
  {
    country: 'Israel',
    publisher: 'Globes',
    city: 'Rishon LeZion',
    region: 'Etzel',
    lat: 31.9611,
    lon: 34.8015,
    label: 'Globes HQ',
  },
  {
    country: 'Israel',
    publisher: 'Times of Israel',
    city: 'Jerusalem',
    region: 'Washington Street',
    lat: 31.7854,
    lon: 35.2123,
    label: 'Times of Israel HQ',
  },
  {
    country: 'Israel',
    publisher: 'Jerusalem Post',
    city: 'Jerusalem',
    region: 'Talpiot',
    lat: 31.7445,
    lon: 35.2142,
    label: 'Jerusalem Post HQ',
  },
  {
    country: 'Israel',
    publisher: 'Ynet',
    city: 'Tel Aviv',
    region: 'Yigal Alon',
    lat: 32.0681,
    lon: 34.7946,
    label: 'Ynet HQ',
  },
  {
    country: 'Israel',
    publisher: 'Haaretz',
    city: 'Tel Aviv',
    region: 'Schocken',
    lat: 32.0538,
    lon: 34.7787,
    label: 'Haaretz HQ',
  },
  {
    country: 'Israel',
    publisher: 'TheMarker',
    city: 'Tel Aviv',
    region: 'Schocken',
    lat: 32.0538,
    lon: 34.7787,
    label: 'TheMarker HQ',
  },
  {
    country: 'Israel',
    publisher: 'Walla',
    city: 'Tel Aviv',
    region: 'Ibn Gabirol',
    lat: 32.0875,
    lon: 34.7818,
    label: 'Walla HQ',
  },
  {
    country: 'Israel',
    publisher: 'mako',
    city: 'Tel Aviv',
    region: 'Raoul Wallenberg',
    lat: 32.109,
    lon: 34.8405,
    label: 'mako HQ',
  },
  {
    country: 'Israel',
    publisher: 'Maariv',
    city: 'Tel Aviv',
    region: 'Menahem Begin',
    lat: 32.0712,
    lon: 34.7926,
    label: 'Maariv HQ',
  },
  {
    country: 'Israel',
    publisher: 'Israel Hayom',
    city: 'Jerusalem',
    region: 'Har Hotzvim',
    lat: 31.8233,
    lon: 35.1885,
    label: 'Israel Hayom HQ',
  },
  {
    country: 'Germany',
    publisher: 'Der Spiegel',
    city: 'Hamburg',
    region: 'HafenCity',
    lat: 53.5459,
    lon: 10.0037,
    label: 'Der Spiegel HQ',
  },
  {
    country: 'France',
    publisher: 'Le Monde',
    city: 'Paris',
    region: '13th arrondissement',
    lat: 48.8362,
    lon: 2.3701,
    label: 'Le Monde HQ',
  },
  {
    country: 'Brazil',
    publisher: 'Folha de S.Paulo',
    city: 'Sao Paulo',
    region: 'Campos Eliseos',
    lat: -23.5317,
    lon: -46.6485,
    label: 'Folha de S.Paulo HQ',
  },
  {
    country: 'Brazil',
    publisher: 'Grupo Globo',
    city: 'Rio de Janeiro',
    region: 'Jardim Botanico',
    lat: -22.9625,
    lon: -43.2122,
    label: 'Grupo Globo HQ',
  },
  {
    country: 'Brazil',
    publisher: 'UOL',
    city: 'Sao Paulo',
    region: 'Pinheiros',
    lat: -23.5731,
    lon: -46.6896,
    label: 'UOL HQ',
  },
  {
    country: 'Brazil',
    publisher: 'Estadao',
    city: 'Sao Paulo',
    region: 'Limao',
    lat: -23.5008,
    lon: -46.6647,
    label: 'Estadao HQ',
  },
  {
    country: 'Brazil',
    publisher: 'Exame',
    city: 'Sao Paulo',
    region: 'Vila Nova Conceicao',
    lat: -23.5948,
    lon: -46.6755,
    label: 'Exame HQ',
  },
  {
    country: 'Germany',
    publisher: 'Handelsblatt',
    city: 'Dusseldorf',
    region: 'Pempelfort',
    lat: 51.236,
    lon: 6.7955,
    label: 'Handelsblatt HQ',
  },
  {
    country: 'Germany',
    publisher: 'Axel Springer',
    city: 'Berlin',
    region: 'Kreuzberg',
    lat: 52.5072,
    lon: 13.3903,
    label: 'Axel Springer HQ',
  },
  {
    country: 'Germany',
    publisher: 'Suddeutsche Zeitung',
    city: 'Munich',
    region: 'Bogenhausen',
    lat: 48.1374,
    lon: 11.631,
    label: 'Süddeutsche Zeitung HQ',
  },
  {
    country: 'Germany',
    publisher: 'Deutschlandradio',
    city: 'Cologne',
    region: 'Raderberg',
    lat: 50.9063,
    lon: 6.9608,
    label: 'Deutschlandradio HQ',
  },
  {
    country: 'Chile',
    publisher: 'Emol',
    city: 'Santiago',
    region: 'Vitacura',
    lat: -33.3823,
    lon: -70.5943,
    label: 'Emol HQ',
  },
  {
    country: 'Chile',
    publisher: 'Cooperativa',
    city: 'Santiago',
    region: 'Santiago Centro',
    lat: -33.4378,
    lon: -70.6504,
    label: 'Cooperativa HQ',
  },
  {
    country: 'Chile',
    publisher: '24Horas',
    city: 'Santiago',
    region: 'Providencia',
    lat: -33.4304,
    lon: -70.6091,
    label: '24Horas HQ',
  },
  {
    country: 'Chile',
    publisher: 'Meganoticias',
    city: 'Santiago',
    region: 'Macul',
    lat: -33.4977,
    lon: -70.6064,
    label: 'Meganoticias HQ',
  },
  {
    country: 'Chile',
    publisher: 'La Tercera',
    city: 'Santiago',
    region: 'Las Condes',
    lat: -33.412,
    lon: -70.598,
    label: 'La Tercera HQ',
  },
  {
    country: 'Chile',
    publisher: 'BioBioChile',
    city: 'Santiago',
    region: 'Providencia',
    lat: -33.4256,
    lon: -70.6162,
    label: 'BioBioChile HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'NRC',
    city: 'Amsterdam',
    region: 'Centrum',
    lat: 52.3711,
    lon: 4.8934,
    label: 'NRC HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'Hart van Nederland',
    city: 'Hilversum',
    region: 'Bergweg',
    lat: 52.2251,
    lon: 5.1587,
    label: 'Hart van Nederland HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'Omroep West',
    city: 'The Hague',
    region: 'Binckhorst',
    lat: 52.0788,
    lon: 4.3346,
    label: 'Omroep West HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'RTV Utrecht',
    city: 'Utrecht',
    region: 'Papendorp',
    lat: 52.0774,
    lon: 5.0784,
    label: 'RTV Utrecht HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'Omroep Gelderland',
    city: 'Arnhem',
    region: 'Arnhem North',
    lat: 51.9962,
    lon: 5.9118,
    label: 'Omroep Gelderland HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'RTV Oost',
    city: 'Hengelo',
    region: 'Hazenweg',
    lat: 52.2816,
    lon: 6.7934,
    label: 'RTV Oost HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'RTV Noord',
    city: 'Groningen',
    region: 'Helperpark',
    lat: 53.2059,
    lon: 6.5793,
    label: 'RTV Noord HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'Rijnmond',
    city: 'Rotterdam',
    region: 'Lloydkwartier',
    lat: 51.9082,
    lon: 4.4478,
    label: 'Rijnmond HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'RTV Drenthe',
    city: 'Assen',
    region: 'Beilerstraat',
    lat: 52.9954,
    lon: 6.5626,
    label: 'RTV Drenthe HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'L1',
    city: 'Maastricht',
    region: 'Randwyck',
    lat: 50.8352,
    lon: 5.7145,
    label: 'L1 HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'Omroep Zeeland',
    city: 'Oost-Souburg',
    region: 'Kanaalstraat',
    lat: 51.4626,
    lon: 3.5982,
    label: 'Omroep Zeeland HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'Omroep Brabant',
    city: 'Son',
    region: 'Science Park',
    lat: 51.5172,
    lon: 5.4926,
    label: 'Omroep Brabant HQ',
  },
  {
    country: 'Belgium',
    publisher: 'La Libre',
    city: 'Brussels',
    region: 'Etterbeek',
    lat: 50.8372,
    lon: 4.3996,
    label: 'La Libre HQ',
  },
  {
    country: 'Belgium',
    publisher: 'Mediahuis',
    city: 'Antwerp',
    region: 'Linkeroever',
    lat: 51.2192,
    lon: 4.3589,
    label: 'Mediahuis HQ',
  },
  {
    country: 'Thailand',
    publisher: 'Nation TV',
    city: 'Bangkok',
    region: 'Bang Na',
    lat: 13.6636,
    lon: 100.6517,
    label: 'Nation TV HQ',
  },
  {
    country: 'Thailand',
    publisher: 'Daily News',
    city: 'Bangkok',
    region: 'Lak Si',
    lat: 13.8753,
    lon: 100.5794,
    label: 'Daily News HQ',
  },
  {
    country: 'Thailand',
    publisher: 'Sanook',
    city: 'Bangkok',
    region: 'Phra Khanong',
    lat: 13.7173,
    lon: 100.5834,
    label: 'Sanook HQ',
  },
  {
    country: 'Thailand',
    publisher: 'Bangkok Post',
    city: 'Bangkok',
    region: 'Khlong Toei',
    lat: 13.7189,
    lon: 100.5592,
    label: 'Bangkok Post HQ',
  },
  {
    country: 'Thailand',
    publisher: 'Matichon',
    city: 'Bangkok',
    region: 'Chatuchak',
    lat: 13.8208,
    lon: 100.5587,
    label: 'Matichon HQ',
  },
  {
    country: 'Thailand',
    publisher: 'Khaosod',
    city: 'Bangkok',
    region: 'Chatuchak',
    lat: 13.8208,
    lon: 100.5587,
    label: 'Khaosod HQ',
  },
  {
    country: 'Thailand',
    publisher: 'Prachachat',
    city: 'Bangkok',
    region: 'Chatuchak',
    lat: 13.8208,
    lon: 100.5587,
    label: 'Prachachat HQ',
  },
  {
    country: 'Thailand',
    publisher: 'Thai PBS',
    city: 'Bangkok',
    region: 'Lak Si',
    lat: 13.8775,
    lon: 100.5664,
    label: 'Thai PBS HQ',
  },
  {
    country: 'Norway',
    publisher: 'E24',
    city: 'Oslo',
    region: 'Sentrum',
    lat: 59.9116,
    lon: 10.7546,
    label: 'E24 HQ',
  },
  {
    country: 'Norway',
    publisher: 'VG',
    city: 'Oslo',
    region: 'Sentrum',
    lat: 59.9139,
    lon: 10.7428,
    label: 'VG HQ',
  },
  {
    country: 'Norway',
    publisher: 'Aftenposten',
    city: 'Oslo',
    region: 'Sentrum',
    lat: 59.9139,
    lon: 10.7428,
    label: 'Aftenposten HQ',
  },
  {
    country: 'Norway',
    publisher: 'NRK',
    city: 'Oslo',
    region: 'Bjorvika',
    lat: 59.9072,
    lon: 10.7533,
    label: 'NRK HQ',
  },
  {
    country: 'Norway',
    publisher: 'Nettavisen',
    city: 'Oslo',
    region: 'Sentrum',
    lat: 59.9139,
    lon: 10.7422,
    label: 'Nettavisen HQ',
  },
  {
    country: 'Norway',
    publisher: 'DN Media Group',
    city: 'Oslo',
    region: 'Sentrum',
    lat: 59.9155,
    lon: 10.7505,
    label: 'DN Media Group HQ',
  },
  {
    country: 'Norway',
    publisher: 'Finansavisen',
    city: 'Oslo',
    region: 'Skoyen',
    lat: 59.9237,
    lon: 10.6825,
    label: 'Finansavisen HQ',
  },
  {
    country: 'Norway',
    publisher: 'Dagbladet',
    city: 'Oslo',
    region: 'Hasle',
    lat: 59.9249,
    lon: 10.7928,
    label: 'Dagbladet HQ',
  },
  {
    country: 'Norway',
    publisher: 'Dagsavisen',
    city: 'Oslo',
    region: 'Grunerlokka',
    lat: 59.9176,
    lon: 10.7569,
    label: 'Dagsavisen HQ',
  },
  {
    country: 'Denmark',
    publisher: 'Jyllands-Posten',
    city: 'Aarhus',
    region: 'Viby J',
    lat: 56.1305,
    lon: 10.1644,
    label: 'Jyllands-Posten HQ',
  },
  {
    country: 'Denmark',
    publisher: 'Nordjyske',
    city: 'Aalborg',
    region: 'Aalborg',
    lat: 57.0488,
    lon: 9.9217,
    label: 'Nordjyske HQ',
  },
  {
    country: 'South Korea',
    publisher: 'The Korea Economic Daily',
    city: 'Seoul',
    region: 'Jung-gu',
    lat: 37.564,
    lon: 126.998,
    label: 'The Korea Economic Daily HQ',
  },
  {
    country: 'South Korea',
    publisher: 'Seoul Broadcasting System',
    city: 'Seoul',
    region: 'Yangcheon-gu',
    lat: 37.517,
    lon: 126.8666,
    label: 'Seoul Broadcasting System HQ',
  },
  {
    country: 'South Korea',
    publisher: 'Hankyoreh',
    city: 'Seoul',
    region: 'Mapo-gu',
    lat: 37.5637,
    lon: 126.9084,
    label: 'Hankyoreh HQ',
  },
  {
    country: 'South Korea',
    publisher: 'Yonhap News Agency',
    city: 'Seoul',
    region: 'Jongno-gu',
    lat: 37.5735,
    lon: 126.979,
    label: 'Yonhap News Agency HQ',
  },
  {
    country: 'South Korea',
    publisher: 'Maeil Business Newspaper',
    city: 'Seoul',
    region: 'Jung-gu',
    lat: 37.564,
    lon: 126.998,
    label: 'Maeil Business Newspaper HQ',
  },
  {
    country: 'United Kingdom',
    publisher: 'Reach',
    city: 'London',
    region: 'Canary Wharf',
    lat: 51.5049,
    lon: -0.0195,
    label: 'Reach HQ',
  },
  {
    country: 'United Kingdom',
    publisher: 'DMG Media',
    city: 'London',
    region: 'Kensington',
    lat: 51.5012,
    lon: -0.1913,
    label: 'DMG Media HQ',
  },
  {
    country: 'United Kingdom',
    publisher: 'News UK',
    city: 'London',
    region: 'Southwark',
    lat: 51.5051,
    lon: -0.0872,
    label: 'News UK HQ',
  },
  {
    country: 'France',
    publisher: 'CNEWS',
    city: 'Paris',
    region: 'Issy-les-Moulineaux',
    lat: 48.8311,
    lon: 2.266,
    label: 'CNEWS HQ',
  },
  {
    country: 'France',
    publisher: 'BFM TV',
    city: 'Paris',
    region: '9th arrondissement',
    lat: 48.876,
    lon: 2.3374,
    label: 'BFM TV HQ',
  },
  {
    country: 'France',
    publisher: 'Le Monde',
    city: 'Paris',
    region: '13th arrondissement',
    lat: 48.8408,
    lon: 2.3677,
    label: 'Le Monde HQ',
  },
  {
    country: 'France',
    publisher: 'France Info',
    city: 'Paris',
    region: '15th arrondissement',
    lat: 48.8388,
    lon: 2.2713,
    label: 'France Info HQ',
  },
  {
    country: 'France',
    publisher: 'France Medias Monde',
    city: 'Issy-les-Moulineaux',
    region: 'Issy-les-Moulineaux',
    lat: 48.8278,
    lon: 2.2647,
    label: 'France Médias Monde HQ',
  },
  {
    country: 'France',
    publisher: 'Le Figaro',
    city: 'Paris',
    region: '9th arrondissement',
    lat: 48.8728,
    lon: 2.3282,
    label: 'Le Figaro HQ',
  },
  {
    country: 'Spain',
    publisher: '20 Minutos',
    city: 'Madrid',
    region: 'Arganzuela',
    lat: 40.4018,
    lon: -3.6897,
    label: '20 Minutos HQ',
  },
  {
    country: 'Australia',
    publisher: 'Seven West Media',
    city: 'Perth',
    region: 'Osborne Park',
    lat: -31.9121,
    lon: 115.8121,
    label: 'Seven West Media HQ',
  },
  {
    country: 'Austria',
    publisher: 'Der Standard',
    city: 'Vienna',
    region: 'Landstrasse',
    lat: 48.2072,
    lon: 16.3835,
    label: 'Der Standard HQ',
  },
  {
    country: 'Austria',
    publisher: 'Nachrichten.at',
    city: 'Linz',
    region: 'Innere Stadt',
    lat: 48.3031,
    lon: 14.2853,
    label: 'Nachrichten.at HQ',
  },
  {
    country: 'Czech Republic',
    publisher: 'Sport.cz',
    city: 'Prague',
    region: 'Smichov',
    lat: 50.0711,
    lon: 14.4009,
    label: 'Sport.cz HQ',
  },
  {
    country: 'Czech Republic',
    publisher: 'Blesk',
    city: 'Prague',
    region: 'Strasnice',
    lat: 50.0782,
    lon: 14.4801,
    label: 'Blesk HQ',
  },
  {
    country: 'Czech Republic',
    publisher: 'TN Nova',
    city: 'Prague',
    region: 'Hlubocepy',
    lat: 50.0301,
    lon: 14.3922,
    label: 'TN Nova HQ',
  },
  {
    country: 'Czech Republic',
    publisher: 'Ceska televize',
    city: 'Prague',
    region: 'Kavci Hory',
    lat: 50.0532,
    lon: 14.4202,
    label: 'Ceska televize HQ',
  },
  {
    country: 'Czech Republic',
    publisher: 'Economia',
    city: 'Prague',
    region: 'Karlin',
    lat: 50.0924,
    lon: 14.4488,
    label: 'Economia HQ',
  },
  {
    country: 'Czech Republic',
    publisher: 'Seznam.cz',
    city: 'Prague',
    region: 'Smichov',
    lat: 50.0623,
    lon: 14.3958,
    label: 'Seznam.cz HQ',
  },
  {
    country: 'Czech Republic',
    publisher: 'MAFRA',
    city: 'Prague',
    region: 'Smichov',
    lat: 50.0711,
    lon: 14.4009,
    label: 'MAFRA HQ',
  },
  {
    country: 'Czech Republic',
    publisher: 'Cesky rozhlas',
    city: 'Prague',
    region: 'Vinohrady',
    lat: 50.0763,
    lon: 14.4375,
    label: 'Cesky rozhlas HQ',
  },
  {
    country: 'Czech Republic',
    publisher: 'FTV Prima',
    city: 'Prague',
    region: 'Strasnice',
    lat: 50.0786,
    lon: 14.4958,
    label: 'FTV Prima HQ',
  },
  {
    country: 'Czech Republic',
    publisher: 'Czech News Center',
    city: 'Prague',
    region: 'Strasnice',
    lat: 50.0782,
    lon: 14.4801,
    label: 'Czech News Center HQ',
  },
  {
    country: 'Czech Republic',
    publisher: 'Denik',
    city: 'Prague',
    region: 'Smichov',
    lat: 50.0724,
    lon: 14.3898,
    label: 'Denik HQ',
  },
  {
    country: 'Denmark',
    publisher: 'DR',
    city: 'Copenhagen',
    region: 'Amager',
    lat: 55.6636,
    lon: 12.5854,
    label: 'DR HQ',
  },
  {
    country: 'Denmark',
    publisher: 'Politiken',
    city: 'Copenhagen',
    region: 'City Hall Square',
    lat: 55.6757,
    lon: 12.5688,
    label: 'Politiken HQ',
  },
  {
    country: 'Denmark',
    publisher: 'Borsen',
    city: 'Copenhagen',
    region: 'Indre By',
    lat: 55.6805,
    lon: 12.5781,
    label: 'Borsen HQ',
  },
  {
    country: 'Denmark',
    publisher: 'Berlingske Media',
    city: 'Copenhagen',
    region: 'Indre By',
    lat: 55.6816,
    lon: 12.5795,
    label: 'Berlingske Media HQ',
  },
  {
    country: 'Denmark',
    publisher: 'Information',
    city: 'Copenhagen',
    region: 'Frederiksstaden',
    lat: 55.6849,
    lon: 12.5856,
    label: 'Information HQ',
  },
  {
    country: 'Bulgaria',
    publisher: 'Vesti',
    city: 'Sofia',
    region: 'Iskar',
    lat: 42.6738,
    lon: 23.4024,
    label: 'Vesti HQ',
  },
  {
    country: 'Turkey',
    publisher: 'TRT Haber',
    city: 'Ankara',
    region: 'Or-An',
    lat: 39.8707,
    lon: 32.8606,
    label: 'TRT Haber HQ',
  },
  {
    country: 'Turkey',
    publisher: 'Hürriyet',
    city: 'Istanbul',
    region: 'Bagcilar',
    lat: 41.0347,
    lon: 28.8262,
    label: 'Hurriyet HQ',
  },
  {
    country: 'Turkey',
    publisher: 'CNN Türk',
    city: 'Istanbul',
    region: 'Bagcilar',
    lat: 41.0347,
    lon: 28.8262,
    label: 'CNN Türk HQ',
  },
  {
    country: 'Turkey',
    publisher: 'Sabah',
    city: 'Istanbul',
    region: 'Bagcilar',
    lat: 41.0347,
    lon: 28.8262,
    label: 'Sabah HQ',
  },
  {
    country: 'Turkey',
    publisher: 'Haber Global',
    city: 'Istanbul',
    region: 'Basaksehir',
    lat: 41.0885,
    lon: 28.8078,
    label: 'Haber Global HQ',
  },
  {
    country: 'Switzerland',
    publisher: 'Watson',
    city: 'Aarau',
    region: 'Rohr',
    lat: 47.3977,
    lon: 8.0659,
    label: 'Watson HQ',
  },
  {
    country: 'Switzerland',
    publisher: 'Blick',
    city: 'Zurich',
    region: 'Seefeld',
    lat: 47.364,
    lon: 8.5535,
    label: 'Blick HQ',
  },
  {
    country: 'Switzerland',
    publisher: 'Blick FR',
    city: 'Lausanne',
    region: 'Lausanne Centre',
    lat: 46.5197,
    lon: 6.6323,
    label: 'Blick FR HQ',
  },
  {
    country: 'Switzerland',
    publisher: 'Le Matin',
    city: 'Lausanne',
    region: 'Sevelin',
    lat: 46.5217,
    lon: 6.6112,
    label: 'Le Matin HQ',
  },
  {
    country: 'Switzerland',
    publisher: '20 Minuten',
    city: 'Zurich',
    region: 'Aussersihl',
    lat: 47.3742,
    lon: 8.526,
    label: '20 Minuten HQ',
  },
  {
    country: 'Switzerland',
    publisher: '20 Minutes',
    city: 'Zurich',
    region: 'Aussersihl',
    lat: 47.3742,
    lon: 8.526,
    label: '20 Minutes HQ',
  },
  {
    country: 'Switzerland',
    publisher: 'Tribune de Geneve',
    city: 'Geneva',
    region: 'Saint-Gervais',
    lat: 46.2053,
    lon: 6.141,
    label: 'Tribune de Geneve HQ',
  },
  {
    country: 'Switzerland',
    publisher: 'NZZ',
    city: 'Zurich',
    region: 'Seefeld',
    lat: 47.366,
    lon: 8.5488,
    label: 'NZZ HQ',
  },
  {
    country: 'Switzerland',
    publisher: 'SRF',
    city: 'Zurich',
    region: 'Leutschenbach',
    lat: 47.4145,
    lon: 8.5493,
    label: 'SRF HQ',
  },
  {
    country: 'Switzerland',
    publisher: 'Swissinfo',
    city: 'Bern',
    region: 'Mattenhof',
    lat: 46.9428,
    lon: 7.4314,
    label: 'Swissinfo HQ',
  },
  {
    country: 'Switzerland',
    publisher: 'Le Temps',
    city: 'Lausanne',
    region: 'Flon',
    lat: 46.5193,
    lon: 6.6285,
    label: 'Le Temps HQ',
  },
  {
    country: 'Norway',
    publisher: 'TV2',
    city: 'Bergen',
    region: 'Nygard',
    lat: 60.3855,
    lon: 5.3328,
    label: 'TV2 HQ',
  },
  {
    country: 'Lithuania',
    publisher: 'Delfi Lithuania',
    city: 'Vilnius',
    region: 'Gynėjų g.',
    lat: 54.6997,
    lon: 25.2588,
    label: 'Delfi Lithuania HQ',
  },
  {
    country: 'Lithuania',
    publisher: 'TV3 Lithuania',
    city: 'Vilnius',
    region: 'Zirmunai',
    lat: 54.7119,
    lon: 25.2978,
    label: 'TV3 Lithuania HQ',
  },
  {
    country: 'Singapore',
    publisher: 'Mediacorp',
    city: 'Singapore',
    region: 'Mediacorp Campus',
    lat: 1.2954,
    lon: 103.7923,
    label: 'Mediacorp HQ',
  },
  {
    country: 'Singapore',
    publisher: 'SPH Media',
    city: 'Singapore',
    region: 'Toa Payoh',
    lat: 1.3359,
    lon: 103.8508,
    label: 'SPH Media HQ',
  },
  {
    country: 'Finland',
    publisher: 'Helsingin Sanomat',
    city: 'Helsinki',
    region: 'Toolonlahti',
    lat: 60.1737,
    lon: 24.9361,
    label: 'Helsingin Sanomat HQ',
  },
  {
    country: 'Finland',
    publisher: 'Ilta-Sanomat',
    city: 'Helsinki',
    region: 'Toolonlahti',
    lat: 60.1737,
    lon: 24.9361,
    label: 'Ilta-Sanomat HQ',
  },
  {
    country: 'Finland',
    publisher: 'Iltalehti',
    city: 'Helsinki',
    region: 'Kamppi',
    lat: 60.1695,
    lon: 24.9257,
    label: 'Iltalehti HQ',
  },
  {
    country: 'Finland',
    publisher: 'Talouselama',
    city: 'Helsinki',
    region: 'Kamppi',
    lat: 60.1695,
    lon: 24.9257,
    label: 'Talouselama HQ',
  },
  {
    country: 'Finland',
    publisher: 'MTV Uutiset',
    city: 'Helsinki',
    region: 'Vallila',
    lat: 60.1927,
    lon: 24.9576,
    label: 'MTV Uutiset HQ',
  },
  {
    country: 'Finland',
    publisher: 'Kauppalehti',
    city: 'Helsinki',
    region: 'Kamppi',
    lat: 60.1695,
    lon: 24.9257,
    label: 'Kauppalehti HQ',
  },
  {
    country: 'Australia',
    publisher: 'The Guardian Australia',
    city: 'Sydney',
    region: 'Surry Hills',
    lat: -33.8834,
    lon: 151.2098,
    label: 'The Guardian Australia HQ',
  },
  {
    country: 'Canada',
    publisher: 'Global News',
    city: 'Toronto',
    region: 'East Bayfront',
    lat: 43.6414,
    lon: -79.3572,
    label: 'Global News HQ',
  },
  {
    country: 'Canada',
    publisher: 'CP24',
    city: 'Toronto',
    region: 'Scarborough',
    lat: 43.7789,
    lon: -79.2647,
    label: 'CP24 HQ',
  },
  {
    country: 'Canada',
    publisher: 'Noovo Info',
    city: 'Montreal',
    region: 'Ville-Marie',
    lat: 45.5192,
    lon: -73.5565,
    label: 'Noovo Info HQ',
  },
  {
    country: 'Canada',
    publisher: 'Bell Media',
    city: 'Toronto',
    region: 'Downtown West',
    lat: 43.6491,
    lon: -79.3863,
    label: 'Bell Media HQ',
  },
  {
    country: 'Canada',
    publisher: 'Postmedia',
    city: 'Toronto',
    region: 'Bloor-Yorkville',
    lat: 43.6719,
    lon: -79.3784,
    label: 'Postmedia HQ',
  },
  {
    country: 'Canada',
    publisher: 'CBC',
    city: 'Toronto',
    region: 'Entertainment District',
    lat: 43.6448,
    lon: -79.3894,
    label: 'CBC HQ',
  },
  {
    country: 'Canada',
    publisher: 'Radio-Canada',
    city: 'Toronto',
    region: 'Entertainment District',
    lat: 43.6448,
    lon: -79.3894,
    label: 'Radio-Canada HQ',
  },
  {
    country: 'Canada',
    publisher: 'Quebecor',
    city: 'Montreal',
    region: 'Ville-Marie',
    lat: 45.4975,
    lon: -73.5568,
    label: 'Quebecor HQ',
  },
  {
    country: 'Canada',
    publisher: 'Toronto Star',
    city: 'Toronto',
    region: 'CityPlace',
    lat: 43.6428,
    lon: -79.3958,
    label: 'Toronto Star HQ',
  },
  {
    country: 'Canada',
    publisher: 'Torstar',
    city: 'Toronto',
    region: 'CityPlace',
    lat: 43.6428,
    lon: -79.3958,
    label: 'Torstar HQ',
  },
  {
    country: 'Canada',
    publisher: 'The Globe and Mail',
    city: 'Toronto',
    region: 'Corktown',
    lat: 43.6514,
    lon: -79.3658,
    label: 'The Globe and Mail HQ',
  },
  {
    country: 'Canada',
    publisher: 'Rogers Sports & Media',
    city: 'Toronto',
    region: 'Rosedale',
    lat: 43.6879,
    lon: -79.3931,
    label: 'Rogers Sports & Media HQ',
  },
  {
    country: 'Egypt',
    publisher: 'Masrawy',
    city: 'Giza',
    region: 'Mohandessin',
    lat: 30.0541,
    lon: 31.2007,
    label: 'Masrawy HQ',
  },
  {
    country: 'France',
    publisher: '20 Minutes',
    city: 'Paris',
    region: '15th arrondissement',
    lat: 48.8389,
    lon: 2.314,
    label: '20 Minutes HQ',
  },
  {
    country: 'Germany',
    publisher: 'Tagesschau',
    city: 'Hamburg',
    region: 'Lokstedt',
    lat: 53.5942,
    lon: 9.9494,
    label: 'Tagesschau HQ',
  },
  {
    country: 'Germany',
    publisher: 'Die Zeit',
    city: 'Hamburg',
    region: 'Altstadt',
    lat: 53.5507,
    lon: 10.0012,
    label: 'Die Zeit HQ',
  },
  {
    country: 'Germany',
    publisher: 'Frankfurter Allgemeine',
    city: 'Frankfurt am Main',
    region: 'Bockenheim',
    lat: 50.1175,
    lon: 8.6481,
    label: 'Frankfurter Allgemeine HQ',
  },
  {
    country: 'Germany',
    publisher: 'Tagesspiegel',
    city: 'Berlin',
    region: 'Kreuzberg',
    lat: 52.5047,
    lon: 13.3808,
    label: 'Tagesspiegel HQ',
  },
  {
    country: 'Indonesia',
    publisher: 'Sindo News',
    city: 'Jakarta',
    region: 'Central Jakarta',
    lat: -6.1872,
    lon: 106.8249,
    label: 'Sindo News HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'DPG Media Netherlands',
    city: 'Amsterdam',
    region: 'Overamstel',
    lat: 52.3369,
    lon: 4.9299,
    label: 'DPG Media Netherlands HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'NOS',
    city: 'Hilversum',
    region: 'Media Park',
    lat: 52.2368,
    lon: 5.177,
    label: 'NOS HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'NPO',
    city: 'Hilversum',
    region: 'Media Park',
    lat: 52.2368,
    lon: 5.177,
    label: 'NPO HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'FD Mediagroep',
    city: 'Amsterdam',
    region: 'Watergraafsmeer',
    lat: 52.3468,
    lon: 4.9188,
    label: 'FD Mediagroep HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'De Telegraaf',
    city: 'Amsterdam',
    region: 'Westpoort',
    lat: 52.3923,
    lon: 4.8289,
    label: 'De Telegraaf HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'RTL Nederland',
    city: 'Hilversum',
    region: 'Media Park',
    lat: 52.2368,
    lon: 5.177,
    label: 'RTL Nederland HQ',
  },
  {
    country: 'Netherlands',
    publisher: 'AT5',
    city: 'Amsterdam',
    region: 'Centrum',
    lat: 52.3667,
    lon: 4.8945,
    label: 'AT5 HQ',
  },
  {
    country: 'Spain',
    publisher: 'ABC.es',
    city: 'Madrid',
    region: 'San Blas-Canillejas',
    lat: 40.4402,
    lon: -3.6367,
    label: 'ABC.es HQ',
  },
  {
    country: 'Spain',
    publisher: 'El Periódico',
    city: 'Barcelona',
    region: "L'Hospitalet de Llobregat",
    lat: 41.3596,
    lon: 2.1314,
    label: 'El Periódico HQ',
  },
  {
    country: 'Argentina',
    publisher: 'Ambito',
    city: 'Buenos Aires',
    region: 'Palermo',
    lat: -34.5798,
    lon: -58.4321,
    label: 'Ambito HQ',
  },
  {
    country: 'Argentina',
    publisher: 'Pagina/12',
    city: 'Buenos Aires',
    region: 'Monserrat',
    lat: -34.6118,
    lon: -58.3794,
    label: 'Pagina/12 HQ',
  },
  {
    country: 'Argentina',
    publisher: 'Clarin',
    city: 'Buenos Aires',
    region: 'Barracas',
    lat: -34.6435,
    lon: -58.3734,
    label: 'Clarin HQ',
  },
  {
    country: 'Argentina',
    publisher: 'La Nacion',
    city: 'Vicente Lopez',
    region: 'Vicente Lopez',
    lat: -34.5261,
    lon: -58.4747,
    label: 'La Nacion HQ',
  },
  {
    country: 'Argentina',
    publisher: 'El Cronista',
    city: 'Buenos Aires',
    region: 'Monserrat',
    lat: -34.6122,
    lon: -58.3689,
    label: 'El Cronista HQ',
  },
  {
    country: 'Argentina',
    publisher: 'C5N',
    city: 'Buenos Aires',
    region: 'Barracas',
    lat: -34.6435,
    lon: -58.3734,
    label: 'C5N HQ',
  },
  {
    country: 'Argentina',
    publisher: 'Infobae',
    city: 'Buenos Aires',
    region: 'Puerto Madero',
    lat: -34.6033,
    lon: -58.3628,
    label: 'Infobae HQ',
  },
  {
    country: 'Argentina',
    publisher: 'TN',
    city: 'Buenos Aires',
    region: 'Barracas',
    lat: -34.6435,
    lon: -58.3734,
    label: 'TN HQ',
  },
  {
    country: 'Argentina',
    publisher: 'MDZ Online',
    city: 'Mendoza',
    region: 'Mendoza',
    lat: -32.8895,
    lon: -68.8458,
    label: 'MDZ Online HQ',
  },
  {
    country: 'Taiwan',
    publisher: 'Yahoo',
    city: 'Taipei',
    region: 'Nangang',
    lat: 25.0556,
    lon: 121.6075,
    label: 'Yahoo Taiwan HQ',
  },
  {
    country: 'Uruguay',
    publisher: 'El Observador',
    city: 'Montevideo',
    region: 'Palermo',
    lat: -34.9097,
    lon: -56.1854,
    label: 'El Observador HQ',
  },
  {
    country: 'Uruguay',
    publisher: 'El Pais Uruguay',
    city: 'Montevideo',
    region: 'Centro',
    lat: -34.9049,
    lon: -56.1915,
    label: 'El Pais Uruguay HQ',
  },
  {
    country: 'Uruguay',
    publisher: 'Montevideo Portal',
    city: 'Montevideo',
    region: 'Cordon',
    lat: -34.9059,
    lon: -56.1767,
    label: 'Montevideo Portal HQ',
  },
  {
    country: 'Uruguay',
    publisher: 'Subrayado',
    city: 'Montevideo',
    region: 'Centro',
    lat: -34.9042,
    lon: -56.1891,
    label: 'Subrayado HQ',
  },
  {
    country: 'Thailand',
    publisher: 'Thairath',
    city: 'Bangkok',
    region: 'Chatuchak',
    lat: 13.8201,
    lon: 100.5595,
    label: 'Thairath HQ',
  },
  {
    country: 'Thailand',
    publisher: 'Bangkok Biz News',
    city: 'Bangkok',
    region: 'Bang Na',
    lat: 13.6678,
    lon: 100.6345,
    label: 'Bangkok Biz News HQ',
  },
  {
    country: 'Belgium',
    publisher: 'VRT',
    city: 'Brussels',
    region: 'Schaerbeek',
    lat: 50.8465,
    lon: 4.4035,
    label: 'VRT HQ',
  },
  {
    country: 'Belgium',
    publisher: 'RTBF',
    city: 'Brussels',
    region: 'Schaerbeek',
    lat: 50.8465,
    lon: 4.4035,
    label: 'RTBF HQ',
  },
  {
    country: 'Belgium',
    publisher: 'DPG Media Belgium',
    city: 'Vilvoorde',
    region: 'Medialaan',
    lat: 50.9226,
    lon: 4.4314,
    label: 'DPG Media Belgium HQ',
  },
  {
    country: 'Poland',
    publisher: 'TVN24',
    city: 'Warsaw',
    region: 'Mokotow',
    lat: 52.1798,
    lon: 21.0513,
    label: 'TVN24 HQ',
  },
  {
    country: 'Poland',
    publisher: 'Polsat News',
    city: 'Warsaw',
    region: 'Praga-Poludnie',
    lat: 52.2297,
    lon: 21.1022,
    label: 'Polsat News HQ',
  },
  {
    country: 'Poland',
    publisher: 'RMF24',
    city: 'Krakow',
    region: 'Salwator',
    lat: 50.0553,
    lon: 19.9172,
    label: 'RMF24 HQ',
  },
  {
    country: 'Poland',
    publisher: 'Radio Zet',
    city: 'Warsaw',
    region: 'Srodmiescie',
    lat: 52.2297,
    lon: 21.0141,
    label: 'Radio Zet HQ',
  },
  {
    country: 'Poland',
    publisher: 'Telewizja Polska',
    city: 'Warsaw',
    region: 'Mokotow',
    lat: 52.1878,
    lon: 21.0014,
    label: 'Telewizja Polska HQ',
  },
  {
    country: 'Poland',
    publisher: 'PAP',
    city: 'Warsaw',
    region: 'Srodmiescie',
    lat: 52.2316,
    lon: 21.0177,
    label: 'PAP HQ',
  },
  {
    country: 'Poland',
    publisher: 'Agora',
    city: 'Warsaw',
    region: 'Mokotow',
    lat: 52.214,
    lon: 21.0449,
    label: 'Agora HQ',
  },
  {
    country: 'Sweden',
    publisher: 'TV4',
    city: 'Stockholm',
    region: 'Gardet',
    lat: 59.3446,
    lon: 18.1039,
    label: 'TV4 HQ',
  },
  {
    country: 'Sweden',
    publisher: 'Dagens Nyheter',
    city: 'Stockholm',
    region: 'Kungsholmen',
    lat: 59.3347,
    lon: 18.0286,
    label: 'Dagens Nyheter HQ',
  },
  {
    country: 'Sweden',
    publisher: 'Dagens Industri',
    city: 'Stockholm',
    region: 'Kungsholmen',
    lat: 59.3347,
    lon: 18.0286,
    label: 'Dagens Industri HQ',
  },
  {
    country: 'Sweden',
    publisher: 'SVT',
    city: 'Stockholm',
    region: 'Garnisonen',
    lat: 59.3396,
    lon: 18.1014,
    label: 'SVT HQ',
  },
  {
    country: 'Sweden',
    publisher: 'Aftonbladet',
    city: 'Stockholm',
    region: 'Norrmalm',
    lat: 59.3318,
    lon: 18.0551,
    label: 'Aftonbladet HQ',
  },
  {
    country: 'Sweden',
    publisher: 'Expressen',
    city: 'Stockholm',
    region: 'Kungsholmen',
    lat: 59.3347,
    lon: 18.0286,
    label: 'Expressen HQ',
  },
  {
    country: 'Sweden',
    publisher: 'Svenska Dagbladet',
    city: 'Stockholm',
    region: 'Norrmalm',
    lat: 59.3318,
    lon: 18.0551,
    label: 'Svenska Dagbladet HQ',
  },
  {
    country: 'Sweden',
    publisher: 'Sveriges Radio',
    city: 'Stockholm',
    region: 'Garnisonen',
    lat: 59.3386,
    lon: 18.1015,
    label: 'Sveriges Radio HQ',
  },
  {
    country: 'United States',
    publisher: 'CNN',
    city: 'Atlanta',
    region: 'Downtown',
    lat: 33.757,
    lon: -84.3963,
    label: 'CNN HQ',
  },
  {
    country: 'United States',
    publisher: 'The New York Times',
    city: 'New York City',
    region: 'Midtown West',
    lat: 40.7554,
    lon: -73.9903,
    label: 'The New York Times HQ',
  },
  {
    country: 'United States',
    publisher: 'Wall Street Journal',
    city: 'New York City',
    region: 'Midtown',
    lat: 40.7613,
    lon: -73.9828,
    label: 'Wall Street Journal HQ',
  },
  {
    country: 'United States',
    publisher: 'Associated Press',
    city: 'New York City',
    region: 'Lower Manhattan',
    lat: 40.7116,
    lon: -74.0154,
    label: 'Associated Press HQ',
  },
  {
    country: 'United States',
    publisher: 'Washington Post',
    city: 'Washington',
    region: 'Downtown',
    lat: 38.9027,
    lon: -77.0301,
    label: 'Washington Post HQ',
  },
  {
    country: 'United States',
    publisher: 'NPR',
    city: 'Washington',
    region: 'NoMa',
    lat: 38.9049,
    lon: -77.009,
    label: 'NPR HQ',
  },
  {
    country: 'United States',
    publisher: 'ABC News',
    city: 'New York City',
    region: 'Lincoln Square',
    lat: 40.7738,
    lon: -73.9813,
    label: 'ABC News HQ',
  },
  {
    country: 'United States',
    publisher: 'Fox News',
    city: 'New York City',
    region: 'Midtown',
    lat: 40.7613,
    lon: -73.9828,
    label: 'Fox News HQ',
  },
  {
    country: 'United States',
    publisher: 'NBC News',
    city: 'New York City',
    region: 'Midtown',
    lat: 40.7587,
    lon: -73.9787,
    label: 'NBC News HQ',
  },
  {
    country: 'United States',
    publisher: 'CBS News',
    city: 'New York City',
    region: 'Hells Kitchen',
    lat: 40.7694,
    lon: -73.9887,
    label: 'CBS News HQ',
  },
  {
    country: 'United States',
    publisher: 'Axios',
    city: 'Arlington',
    region: 'Arlington',
    lat: 38.8803,
    lon: -77.1083,
    label: 'Axios HQ',
  },
  {
    country: 'United States',
    publisher: 'Arizona Republic',
    city: 'Phoenix',
    region: 'Downtown',
    lat: 33.4483,
    lon: -112.0739,
    label: 'Arizona Republic HQ',
  },
  {
    country: 'United States',
    publisher: 'Baltimore Sun',
    city: 'Baltimore',
    region: 'Downtown',
    lat: 39.2864,
    lon: -76.615,
    label: 'Baltimore Sun HQ',
  },
  {
    country: 'United States',
    publisher: 'Billboard',
    city: 'New York City',
    region: 'Lower Manhattan',
    lat: 40.7206,
    lon: -74.0058,
    label: 'Billboard HQ',
  },
  {
    country: 'United States',
    publisher: 'Bloomberg',
    city: 'New York City',
    region: 'Midtown East',
    lat: 40.7618,
    lon: -73.968,
    label: 'Bloomberg HQ',
  },
  {
    country: 'United States',
    publisher: 'Boston Globe',
    city: 'Boston',
    region: 'Exchange Place',
    lat: 42.3588,
    lon: -71.0577,
    label: 'Boston Globe HQ',
  },
  {
    country: 'United States',
    publisher: 'Business Insider',
    city: 'New York City',
    region: 'Flatiron',
    lat: 40.7422,
    lon: -73.9896,
    label: 'Business Insider HQ',
  },
  {
    country: 'United States',
    publisher: 'Chicago Tribune',
    city: 'Chicago',
    region: 'River North',
    lat: 41.8904,
    lon: -87.6237,
    label: 'Chicago Tribune HQ',
  },
];

let generatedPublisherHeadquartersCache: PublisherHeadquartersRecord[] | null = null;

function getGeneratedPublisherHeadquartersPath(): string {
  return path.join(process.cwd(), 'data', 'publisher-headquarters.generated.json');
}

function loadGeneratedPublisherHeadquarters(): PublisherHeadquartersRecord[] {
  if (generatedPublisherHeadquartersCache) return generatedPublisherHeadquartersCache;
  try {
    const raw = readFileSync(getGeneratedPublisherHeadquartersPath(), 'utf8');
    const parsed = JSON.parse(raw) as PublisherHeadquartersRecord[];
    generatedPublisherHeadquartersCache = Array.isArray(parsed) ? parsed : [];
  } catch {
    generatedPublisherHeadquartersCache = [];
  }
  return generatedPublisherHeadquartersCache;
}

function getAllPublisherHeadquarters(): PublisherHeadquartersRecord[] {
  return [...PUBLISHER_HEADQUARTERS, ...loadGeneratedPublisherHeadquarters()];
}

export function resolvePublisherHeadquarters(
  publisher: string | null | undefined,
  country: string
): ResolvedPublisherHeadquarters | null {
  if (!publisher) return null;
  const normalizedPublisher = normalizePublisher(publisher);
  const record = getAllPublisherHeadquarters().find(
    (entry) => entry.country === country && normalizePublisher(entry.publisher) === normalizedPublisher
  );
  if (!record) return null;
  return {
    city: record.city,
    region: record.region,
    lat: record.lat,
    lon: record.lon,
    label: record.label,
  };
}
