import { buildDisplaySourceName } from '@/lib/source-display';

export type PublisherConfidence = 'high' | 'medium' | 'low';
type PublisherMatchType = 'exact' | 'prefix' | 'contains' | 'fallback';

type PublisherRule = {
  publisher: string;
  countries?: string[];
  exact?: string[];
  prefixes?: string[];
  contains?: string[];
  confidence?: PublisherConfidence;
};

export type ResolvedPublisher = {
  publisher: string;
  confidence: PublisherConfidence;
  matchedBy: PublisherMatchType;
};

function normalize(value: string): string {
  return buildDisplaySourceName(value || '').trim().toLowerCase();
}

const PUBLISHER_RULES: PublisherRule[] = [
  { publisher: 'Yahoo', exact: ['Yahoo'], prefixes: ['Yahoo '] },
  { publisher: 'BBC', prefixes: ['BBC '] },
  { publisher: 'Associated Press', exact: ['Associated Press', 'AP News'] },
  { publisher: 'Reuters', prefixes: ['Reuters'] },
  {
    publisher: 'Mediacorp',
    prefixes: ['CNA', 'TODAY', '8world', 'BERITA Mediacorp', 'Seithi Mediacorp'],
    countries: ['Singapore'],
  },
  {
    publisher: 'SPH Media',
    prefixes: [
      'The Straits Times',
      'Straits Times',
      'The Business Times',
      'Business Times',
      'Lianhe Zaobao',
      'Zaobao',
      'Berita Harian',
      'Tamil Murasu',
      'Shin Min',
      'STOMP',
      'AsiaOne',
      'ThinkChina',
      'tabla!',
    ],
    countries: ['Singapore'],
  },

  {
    publisher: 'Nine Entertainment',
    countries: ['Australia'],
    exact: ['The Sydney Morning Herald', 'The Age', 'Brisbane Times', 'WAtoday', 'AFR', 'Australian Financial Review'],
    prefixes: ['SMH', 'The Age', 'Brisbane Times', 'WAtoday', 'AFR -', 'Sydney Morning Herald'],
  },
  {
    publisher: 'News Corp Australia',
    countries: ['Australia'],
    prefixes: [
      'News.com.au',
      'The Australian',
      'Herald Sun',
      'Daily Telegraph Australia',
      'Courier Mail',
      'AdelaideNow',
      'Townsville Bulletin',
      'Gold Coast Bulletin',
      'NT News',
      'The Mercury',
      'Geelong Advertiser',
      'Cairns Post',
      'The Daily Telegraph',
    ],
  },
  {
    publisher: 'Seven West Media',
    countries: ['Australia'],
    prefixes: ['7news', 'The West Australian', 'PerthNow', 'The Nightly'],
  },
  {
    publisher: 'Australian Broadcasting Corporation',
    countries: ['Australia'],
    prefixes: ['ABC News', 'ABC -', 'ABC ', 'Australian Broadcasting Corporation -'],
  },
  {
    publisher: 'Nine Entertainment',
    countries: ['Australia'],
    exact: ['9News', 'AFR (Financial Review)'],
    prefixes: ['9News ', 'AFR ('],
  },
  { publisher: 'SBS', countries: ['Australia'], prefixes: ['SBS'] },
  { publisher: 'AAP', countries: ['Australia'], prefixes: ['AAP'] },
  { publisher: 'DMG Media', countries: ['Australia', 'United Kingdom'], prefixes: ['Daily Mail'] },
  { publisher: 'The Guardian Australia', countries: ['Australia'], prefixes: ['The Guardian Australia'] },
  {
    publisher: 'Australian Community Media',
    countries: ['Australia'],
    prefixes: [
      'Canberra Times',
      'The Chronicle',
      'Weekly Times',
      'Newcastle Herald',
      'Illawarra Mercury',
      'The Courier',
      'Border Mail',
      'The Advocate',
      'Daily Advertiser',
      'Central Western Daily',
      'The Examiner',
      'Bendigo Advertiser',
      'North West Star',
      'Goulburn Post',
      'The Land',
      'Manning River Times',
      'Port Macquarie News',
      'Blue Mountains Gazette',
      'Warrnambool Standard',
      'Daily Liberal',
      'Northern Daily Leader',
      'Western Advocate',
      'Queensland Country Life',
      'North Queensland Register',
      'Stock & Land',
      'Stock Journal',
      'Farmonline',
      'The Senior',
      'Maitland Mercury',
      'Armidale Express',
      'Area News',
      'Singleton Argus',
      'Glen Innes Examiner',
      'Moree Champion',
      'Tenterfield Star',
    ],
  },
  { publisher: 'The Independent', countries: ['United Kingdom'], prefixes: ['The Independent'] },
  { publisher: 'Reach', countries: ['United Kingdom'], prefixes: ['Mirror', 'Daily Express', 'Manchester Evening News'] },
  {
    publisher: 'Reach',
    countries: ['Ireland'],
    exact: ['Irish Mirror', 'DublinLive', 'Irish Star', 'CorkBeo', 'GalwayBeo', 'BelfastLive', 'Buzz.ie'],
    prefixes: ['Irish Mirror -'],
  },
  { publisher: 'News UK', countries: ['United Kingdom'], prefixes: ['The Sun', 'The Times'] },
  { publisher: 'DMG Media', countries: ['United Kingdom'], prefixes: ['Daily Mail', 'Metro'] },
  { publisher: 'DMG Media Ireland', countries: ['Ireland'], exact: ['Extra.ie'], prefixes: ['Extra.ie -'] },
  { publisher: 'Mediahuis Ireland', countries: ['Ireland'], prefixes: ['Independent.ie', 'Sunday World'] },
  { publisher: 'BBC', countries: ['United Kingdom'], prefixes: ['BBC News'] },
  { publisher: 'RTÉ', countries: ['Ireland'], exact: ['RTÉ News', 'RTÉ Sport'], prefixes: ['RTÉ '] },
  { publisher: 'Journal Media', countries: ['Ireland'], exact: ['TheJournal.ie'] },
  { publisher: 'The Irish Times', countries: ['Ireland'], exact: ['Irish Times'] },
  { publisher: 'BreakingNews.ie', countries: ['Ireland'], exact: ['BreakingNews.ie'], prefixes: ['BreakingNews.ie -'] },
  { publisher: 'RTL Nieuws', countries: ['Netherlands'], exact: ['RTL Nieuws (General Breaking)'], prefixes: ['RTL Nieuws'] },
  { publisher: 'Tweakers', countries: ['Netherlands'], exact: ['Tweakers', 'Tweakers (Mixed)'] },
  { publisher: 'BNNVARA', countries: ['Netherlands'], exact: ['BNNVARA'] },
  { publisher: 'Omrop Fryslan', countries: ['Netherlands'], exact: ['Omrop Fryslan'], prefixes: ['Omrop Fryslan -'] },
  {
    publisher: 'DPG Media Netherlands',
    countries: ['Netherlands'],
    prefixes: [
      'AD ',
      'de Volkskrant',
      'Trouw',
      'Het Parool',
      'PZC -',
      'Tubantia -',
      'De Stentor -',
      'De Gelderlander -',
      'Brabants Dagblad -',
      'Eindhovens Dagblad -',
      'BN DeStem -',
    ],
  },

  { publisher: 'Korean Broadcasting System', countries: ['South Korea'], exact: ['KBS News'], prefixes: ['KBS -'] },
  { publisher: 'Yonhap News Agency', countries: ['South Korea'], prefixes: ['Yonhap'] },
  { publisher: 'Seoul Broadcasting System', countries: ['South Korea'], prefixes: ['SBS -'] },
  { publisher: 'JoongAng Group', countries: ['South Korea'], prefixes: ['JTBC -', 'JoongAng -'] },
  { publisher: 'Chosun Ilbo', countries: ['South Korea'], prefixes: ['조선닷컴', 'Chosun'] },
  { publisher: 'Newsis', countries: ['South Korea'], exact: ['Newsis'] },
  { publisher: 'Dong-A Ilbo', countries: ['South Korea'], prefixes: ['Donga Ilbo'] },
  { publisher: 'The Korea Herald', countries: ['South Korea'], prefixes: ['Korea Herald'] },
  { publisher: 'The Korea Times', countries: ['South Korea'], prefixes: ['Korea Times'] },
  { publisher: 'Hankyoreh', countries: ['South Korea'], prefixes: ['한겨레'] },
  { publisher: 'Maeil Business Newspaper', countries: ['South Korea'], prefixes: ['매일경제 -'] },
  { publisher: 'The Korea Economic Daily', countries: ['South Korea'], prefixes: ['한국경제 -'] },

  { publisher: 'Die Presse', countries: ['Austria'], prefixes: ['Die Presse'] },
  { publisher: 'Kleine Zeitung', countries: ['Austria'], prefixes: ['Kleine Zeitung'] },
  { publisher: 'PULS 24', countries: ['Austria'], prefixes: ['PULS 24'] },
  { publisher: 'Heute', countries: ['Austria'], prefixes: ['Heute'] },
  { publisher: 'Kurier', countries: ['Austria'], prefixes: ['Kurier'] },
  { publisher: 'ORF', countries: ['Austria'], prefixes: ['ORF'] },
  { publisher: 'Der Standard', countries: ['Austria'], prefixes: ['derStandard', 'Der Standard'] },
  { publisher: 'VOL.AT', countries: ['Austria'], prefixes: ['VOL.AT'] },
  { publisher: 'profil', countries: ['Austria'], exact: ['profil'], prefixes: ['profil'] },

  {
    publisher: 'NHK',
    countries: ['Japan'],
    exact: ['NHK World (EN)'],
    prefixes: ['NHK News', 'NHK News Web -', 'NHK World'],
  },
  { publisher: 'Nippon Television', countries: ['Japan'], exact: ['NTV'] },
  { publisher: 'Nikkei', countries: ['Japan'], exact: ['Nikkei'] },
  { publisher: 'Jiji Press', countries: ['Japan'], exact: ['Jiji Press'] },
  { publisher: 'Kyodo News', countries: ['Japan'], exact: ['Kyodo News'] },
  { publisher: 'Yomiuri Shimbun', countries: ['Japan'], exact: ['Yomiuri'] },
  { publisher: 'Asahi Shimbun', countries: ['Japan'], exact: ['Asahi Shimbun'] },
  {
    publisher: 'Mainichi Shimbun',
    countries: ['Japan'],
    exact: ['Mainichi', 'Mainichi (Biz)', 'Mainichi Flash'],
    prefixes: ['Mainichi '],
  },
  { publisher: 'The Japan Times', countries: ['Japan'], exact: ['The Japan Times'] },
  { publisher: 'Sponichi', countries: ['Japan'], exact: ['Sponichi'] },
  { publisher: 'Abema', countries: ['Japan'], prefixes: ['Abema'] },
  {
    publisher: 'ITmedia',
    countries: ['Japan'],
    prefixes: ['ITmedia', '@IT'],
  },
  {
    publisher: 'Impress',
    countries: ['Japan'],
    prefixes: ['INTERNET Watch', 'Impress Watch'],
  },
  {
    publisher: 'PR TIMES',
    countries: ['Japan'],
    prefixes: ['PR TIMES'],
  },
  {
    publisher: 'Toyo Keizai',
    countries: ['Japan'],
    exact: ['Toyo Keizai'],
    prefixes: ['Toyo Keizai -'],
  },
  {
    publisher: 'J-CAST',
    countries: ['Japan'],
    exact: ['J-CASTニュース (総合)', 'J-CASTトレンド', 'J-CAST会社ウォッチ', 'BOOKウォッチ'],
  },

  { publisher: 'ANSA', countries: ['Italy'], prefixes: ['ANSA'] },
  { publisher: 'Corriere della Sera', countries: ['Italy'], prefixes: ['Corriere della Sera'] },
  { publisher: 'la Repubblica', countries: ['Italy'], prefixes: ['la Repubblica'] },
  { publisher: 'La Stampa', countries: ['Italy'], prefixes: ['La Stampa'] },
  { publisher: 'Il Sole 24 Ore', countries: ['Italy'], prefixes: ['Il Sole 24 Ore'] },
  { publisher: 'RaiNews', countries: ['Italy'], prefixes: ['RaiNews'] },
  { publisher: 'TgCom24', countries: ['Italy'], prefixes: ['TgCom24'] },
  { publisher: 'Adnkronos', countries: ['Italy'], prefixes: ['Adnkronos'] },
  { publisher: 'AGI', countries: ['Italy'], prefixes: ['AGI'] },
  { publisher: 'Il Messaggero', countries: ['Italy'], prefixes: ['Il Messaggero'] },
  { publisher: 'Il Giornale', countries: ['Italy'], exact: ['Il Giornale'] },
  { publisher: 'Today Network', countries: ['Italy'], exact: ['Today.it', 'MilanoToday'] },
  { publisher: 'Open', countries: ['Italy'], prefixes: ['Open.online'] },

  { publisher: 'RT', countries: ['Russia'], exact: ['RT'], prefixes: ['RT '] },
  { publisher: 'Interfax', countries: ['Russia'], exact: ['Interfax'] },
  { publisher: 'Lenta.ru', countries: ['Russia'], exact: ['Lenta'] },
  { publisher: 'TASS', countries: ['Russia'], prefixes: ['TASS'] },
  { publisher: 'RIA Novosti', countries: ['Russia'], prefixes: ['RIA Novosti'] },
  { publisher: 'RBC', countries: ['Russia'], prefixes: ['RBC'] },
  { publisher: 'Kommersant', countries: ['Russia'], prefixes: ['Kommersant'] },
  { publisher: 'Vedomosti', countries: ['Russia'], prefixes: ['Vedomosti'] },
  { publisher: 'Gazeta.ru', countries: ['Russia'], prefixes: ['Gazeta.ru'] },
  { publisher: 'Rossiyskaya Gazeta', countries: ['Russia'], prefixes: ['Rossiyskaya Gazeta'] },
  { publisher: 'Expert.ru', countries: ['Russia'], prefixes: ['Expert.ru'] },
  { publisher: 'Rambler', countries: ['Russia'], prefixes: ['Rambler'] },
  { publisher: 'The Moscow Times', countries: ['Russia'], exact: ['The Moscow Times'] },

  { publisher: 'CNN', countries: ['United States'], exact: ['CNN'], prefixes: ['CNN '] },
  {
    publisher: 'The New York Times',
    countries: ['United States'],
    exact: ['The New York Times'],
    prefixes: ['The New York Times -'],
  },
  { publisher: 'Wall Street Journal', countries: ['United States'], exact: ['Wall Street Journal'] },
  { publisher: 'USA Today', countries: ['United States'], prefixes: ['USA Today'] },
  {
    publisher: 'LA Times',
    countries: ['United States'],
    exact: ['LA Times'],
    prefixes: ['LA Times -'],
  },
  {
    publisher: 'Fox News',
    countries: ['United States'],
    exact: ['Fox News'],
    prefixes: ['Fox News -'],
  },
  {
    publisher: 'NBC News',
    countries: ['United States'],
    exact: ['NBC News'],
    prefixes: ['NBC News -'],
  },
  {
    publisher: 'CBS News',
    countries: ['United States'],
    exact: ['CBS News'],
    prefixes: ['CBS News -'],
  },
  {
    publisher: 'ABC News',
    countries: ['United States'],
    exact: ['ABC News'],
    prefixes: ['ABC News -'],
  },
  {
    publisher: 'NPR',
    countries: ['United States'],
    exact: ['NPR'],
    prefixes: ['NPR -'],
  },
  {
    publisher: 'Washington Post',
    countries: ['United States'],
    exact: ['Washington Post'],
    prefixes: ['Washington Post -'],
  },
  {
    publisher: 'Politico',
    countries: ['United States'],
    exact: ['Politico'],
    prefixes: ['Politico '],
  },
  {
    publisher: 'CNBC',
    countries: ['United States'],
    exact: ['CNBC'],
    prefixes: ['CNBC '],
  },
  {
    publisher: 'Vox Media',
    countries: ['United States'],
    exact: ['Vox', 'The Verge'],
    prefixes: ['Vox -', 'The Verge -'],
  },
  {
    publisher: 'TechCrunch',
    countries: ['United States'],
    exact: ['TechCrunch'],
    prefixes: ['TechCrunch -'],
  },
  { publisher: 'Masrawy', countries: ['Egypt'], exact: ['Masrawy'], prefixes: ['Masrawy'] },
  {
    publisher: 'Hürriyet',
    countries: ['Turkey'],
    exact: ['Hürriyet'],
    prefixes: ['Hürriyet (', 'Hürriyet '],
  },
  {
    publisher: 'CNN Türk',
    countries: ['Turkey'],
    prefixes: ['CNN Türk ('],
  },
  {
    publisher: 'Sabah',
    countries: ['Turkey'],
    exact: ['Sabah'],
    prefixes: ['Sabah (', 'Sabah '],
  },
  { publisher: 'Tagesschau', countries: ['Germany'], prefixes: ['Tagesschau'] },
  { publisher: 'Die Zeit', countries: ['Germany'], exact: ['Die Zeit'], prefixes: ['Die Zeit'] },
  {
    publisher: 'Frankfurter Allgemeine',
    countries: ['Germany'],
    exact: ['Frankfurter Allgemeine'],
    prefixes: ['Frankfurter Allgemeine', 'FAZ'],
  },
  { publisher: 'Tagesspiegel', countries: ['Germany'], exact: ['Tagesspiegel'], prefixes: ['Tagesspiegel'] },
  {
    publisher: 'Axel Springer',
    countries: ['Germany'],
    prefixes: ['WELT', 'BILD', 'Die Welt'],
  },
  {
    publisher: 'Handelsblatt',
    countries: ['Germany'],
    exact: ['Handelsblatt'],
    prefixes: ['Handelsblatt '],
  },
  {
    publisher: 'Suddeutsche Zeitung',
    countries: ['Germany'],
    exact: ['Süddeutsche'],
    prefixes: ['Süddeutsche -'],
  },
  {
    publisher: 'Deutschlandradio',
    countries: ['Germany'],
    exact: ['Deutschlandfunk'],
    prefixes: ['Deutschlandfunk -'],
  },
  { publisher: '20 Minutes', countries: ['France'], exact: ['20 Minutes'], prefixes: ['20 Minutes'] },
  {
    publisher: 'Le Monde',
    countries: ['France'],
    prefixes: ['Le Monde ('],
  },
  {
    publisher: 'France Medias Monde',
    countries: ['France'],
    exact: ['France 24', 'France 24 (FR)', 'RFI (France)', 'RFI (FR)', 'RFI (All / EN)'],
    prefixes: ['France 24', 'RFI '],
  },
  {
    publisher: 'France Info',
    countries: ['France'],
    prefixes: ['France Info'],
  },
  {
    publisher: 'Le Figaro',
    countries: ['France'],
    exact: ['Le Figaro'],
    prefixes: ['Le Figaro '],
  },
  {
    publisher: 'Folha de S.Paulo',
    countries: ['Brazil'],
    prefixes: ['Folha de S.Paulo -', 'Folha -'],
  },
  {
    publisher: 'Grupo Globo',
    countries: ['Brazil'],
    exact: ['G1 Globo (General Top Portal)', 'G1 Mundo', 'G1 Ciência e Saúde', 'G1 Carros'],
    prefixes: ['G1 (Globo -', 'G1 Política', 'G1 Economia -'],
  },
  {
    publisher: 'UOL',
    countries: ['Brazil'],
    prefixes: ['UOL '],
  },
  {
    publisher: 'Estadao',
    countries: ['Brazil'],
    exact: ['Estadão'],
    prefixes: ['Estadão (', 'Estadão -'],
  },
  {
    publisher: 'Exame',
    countries: ['Brazil'],
    prefixes: ['Exame ('],
  },
  { publisher: 'ABC.es', countries: ['Spain'], exact: ['ABC.es'], prefixes: ['ABC.es'] },
  { publisher: 'El Periódico', countries: ['Spain'], prefixes: ['El Periódico'] },
  { publisher: 'Sindo News', countries: ['Indonesia'], prefixes: ['Sindo News'] },
  { publisher: 'Haber Global', countries: ['Turkey'], exact: ['Haber Global'], prefixes: ['Haber Global'] },
  { publisher: 'Thairath', countries: ['Thailand'], prefixes: ['Thairath'] },
  {
    publisher: 'Daily News',
    countries: ['Thailand'],
    exact: ['Daily News'],
    prefixes: ['Daily News -', 'PressDisplay - Daily News Thailand'],
  },
  {
    publisher: 'Sanook',
    countries: ['Thailand'],
    exact: ['Sanook News (Top Portal)', 'Sanook Economy (Portal Economy)'],
    prefixes: ['Sanook -'],
  },
  {
    publisher: 'Bangkok Biz News',
    countries: ['Thailand'],
    prefixes: ['Bangkok Biz News'],
    exact: ['PressDisplay - Krungthep Turakij'],
  },
  {
    publisher: 'Bangkok Post',
    countries: ['Thailand'],
    exact: ['PressDisplay - Bangkok Post'],
    prefixes: ['Bangkok Post -'],
  },
  {
    publisher: 'Matichon',
    countries: ['Thailand'],
    exact: ['Matichon', 'Matichon (Leading Political Daily)'],
    prefixes: ['Matichon -'],
  },
  {
    publisher: 'Khaosod',
    countries: ['Thailand'],
    exact: ['Khaosod English', 'Khaosod English - Food (category)', 'Khaosod (Popular General News)'],
    prefixes: ['Khaosod -', 'Khaosod English -'],
  },
  {
    publisher: 'Prachachat',
    countries: ['Thailand'],
    exact: ['Prachachat', 'Prachachat (Business/Economy #1)'],
    prefixes: ['Prachachat -'],
  },
  {
    publisher: 'Thai PBS',
    countries: ['Thailand'],
    exact: ['Thai PBS (news feed endpoint)'],
  },
  {
    publisher: 'Azteca Noticias',
    countries: ['Mexico'],
    exact: ['Azteca Noticias'],
    prefixes: ['Azteca Noticias -', 'ADN40 '],
  },
  {
    publisher: 'Excelsior',
    countries: ['Mexico'],
    exact: ['Excelsior', 'Excelsior (보수 유력지)'],
    prefixes: ['Excelsior -'],
  },
  {
    publisher: 'Grupo Milenio',
    countries: ['Mexico'],
    exact: ['Milenio (전국지)'],
    prefixes: ['Milenio '],
  },
  {
    publisher: 'El Universal',
    countries: ['Mexico'],
    prefixes: ['El Universal -'],
  },
  {
    publisher: 'Reforma',
    countries: ['Mexico'],
    prefixes: ['Reforma -'],
  },
  {
    publisher: 'El Economista',
    countries: ['Mexico'],
    exact: ['El Economista - Top Noticias (멕시코 경제 1위)', 'El Economista - Empresas'],
    prefixes: ['El Economista -'],
  },
  {
    publisher: 'Proceso',
    countries: ['Mexico'],
    exact: ['Proceso (Investigative)', 'Proceso World'],
    prefixes: ['Proceso '],
  },
  {
    publisher: 'El Financiero',
    countries: ['Mexico'],
    prefixes: ['El Financiero (', 'El Financiero -'],
  },
  {
    publisher: 'La Jornada',
    countries: ['Mexico'],
    prefixes: ['La Jornada -', 'La Jornada ('],
  },
  { publisher: 'Global News', countries: ['Canada'], prefixes: ['Global News'] },
  { publisher: 'CP24', countries: ['Canada'], prefixes: ['CP24'] },
  { publisher: 'Noovo Info', countries: ['Canada'], prefixes: ['Noovo Info'] },
  {
    publisher: 'Bell Media',
    countries: ['Canada'],
    prefixes: ['CTV News', 'CTV ', 'CTV', 'BNN Bloomberg'],
  },
  {
    publisher: 'CBC',
    countries: ['Canada'],
    prefixes: ['CBC News -', 'CBC '],
  },
  {
    publisher: 'Radio-Canada',
    countries: ['Canada'],
    exact: ['Radio-Canada'],
    prefixes: ['Radio-Canada -'],
  },
  {
    publisher: 'Quebecor',
    countries: ['Canada'],
    prefixes: ['TVA Nouvelles', 'TVA Sports', 'Journal de Montréal', 'Journal de Québec'],
  },
  {
    publisher: 'Torstar',
    countries: ['Canada'],
    prefixes: [
      'Hamilton Spectator',
      'Waterloo Region Record',
      'Niagara Falls Review',
      'St. Catharines Standard',
      'Welland Tribune',
      'Toronto.com',
      'InsideHalton',
      'Guelph Mercury',
      'Peterborough Examiner',
      'Cambridge Times',
    ],
  },
  {
    publisher: 'Toronto Star',
    countries: ['Canada'],
    exact: ['Toronto Star'],
    prefixes: ['Toronto Star -'],
  },
  {
    publisher: 'The Globe and Mail',
    countries: ['Canada'],
    prefixes: ['The Globe and Mail'],
  },
  {
    publisher: 'Rogers Sports & Media',
    countries: ['Canada'],
    prefixes: [
      'CityNews Toronto',
      'CityNews Montreal',
      'CityNews Ottawa',
      'CityNews Edmonton',
      'CityNews Winnipeg',
      'CityNews Kitchener',
      '660 NewsRadio Calgary',
      '1130 NewsRadio Vancouver',
      'HalifaxToday',
    ],
  },
  {
    publisher: 'Postmedia',
    countries: ['Canada'],
    prefixes: [
      'National Post',
      'Financial Post',
      'Toronto Sun',
      'Calgary Herald',
      'Edmonton Journal',
      'Windsor Star',
      'The Province',
      'Calgary Sun',
      'Ottawa Sun',
      'The StarPhoenix',
      'Regina Leader Post',
      'Owen Sound Sun Times',
      'Stratford Beacon Herald',
      'Grande Prairie Daily Herald Tribune',
      'Canada.com',
      'Montreal Gazette',
      'Vancouver Sun',
      'Ottawa Citizen',
      'London Free Press',
      'Kingston Whig-Standard',
      'Sudbury Star',
      'Sarnia Observer',
      'Timmins Press',
      'Brantford Expositor',
      'Chatham Daily News',
      'Standard-Freeholder',
    ],
  },
  {
    publisher: 'DPG Media Netherlands',
    countries: ['Netherlands'],
    exact: ['Nu'],
    prefixes: ['AD', 'AD -', 'de Volkskrant', 'Trouw', 'Het Parool', 'NU.nl', 'Nu.nl'],
  },
  {
    publisher: 'NOS',
    countries: ['Netherlands'],
    exact: ['NOS', 'Nieuwsuur'],
    prefixes: ['NOS', 'NOS Nieuws', 'NOS Sport', 'NOS op 3', 'NOS Jeugdjournaal'],
  },
  { publisher: 'NPO', countries: ['Netherlands'], exact: ['NPO Radio 1'] },
  {
    publisher: 'FD Mediagroep',
    countries: ['Netherlands'],
    exact: ['FD', 'Het Financieele Dagblad (FD)'],
    prefixes: ['FD -', 'BNR', 'BNR Nieuwsradio'],
  },
  { publisher: 'De Telegraaf', countries: ['Netherlands'], prefixes: ['De Telegraaf', 'Telegraaf ('] },
  { publisher: 'RTL Nederland', countries: ['Netherlands'], exact: ['RTL'], prefixes: ['RTL Z'] },
  { publisher: 'Yle', countries: ['Finland'], prefixes: ['Yle'] },
  {
    publisher: 'Helsingin Sanomat',
    countries: ['Finland'],
    exact: ['Helsingin Sanomat'],
    prefixes: ['Helsingin Sanomat -'],
  },
  {
    publisher: 'Ilta-Sanomat',
    countries: ['Finland'],
    exact: ['Ilta-Sanomat'],
    prefixes: ['Ilta-Sanomat -'],
  },
  {
    publisher: 'Iltalehti',
    countries: ['Finland'],
    exact: ['Iltalehti'],
    prefixes: ['Iltalehti -'],
  },
  { publisher: 'Talouselama', countries: ['Finland'], exact: ['Talouselama'], prefixes: ['Talouselama -'] },
  { publisher: 'MTV Uutiset', countries: ['Finland'], prefixes: ['MTV Uutiset'] },
  { publisher: 'Kauppalehti', countries: ['Finland'], exact: ['Kauppalehti'] },
  {
    publisher: 'VG',
    countries: ['Norway'],
    exact: ['VG', 'VG (Verdens Gang)'],
    prefixes: ['VG -'],
  },
  { publisher: 'Aftenposten', countries: ['Norway'], exact: ['Aftenposten'] },
  {
    publisher: 'NRK',
    countries: ['Norway'],
    exact: ['NRK', 'NRK News', 'NRK - RSS oversikt (directory)'],
    prefixes: ['NRK -'],
  },
  {
    publisher: 'E24',
    countries: ['Norway'],
    exact: ['E24'],
    prefixes: ['E24 -'],
  },
  {
    publisher: 'TV2',
    countries: ['Norway'],
    exact: ['TV2'],
    prefixes: ['TV2 -'],
  },
  {
    publisher: 'Jyllands-Posten',
    countries: ['Denmark'],
    exact: ['Jyllands-Posten'],
    prefixes: ['Jyllands-Posten -'],
  },
  {
    publisher: 'Nordjyske',
    countries: ['Denmark'],
    exact: ['Nordjyske'],
    prefixes: ['Nordjyske -'],
  },
  {
    publisher: 'Nettavisen',
    countries: ['Norway'],
    exact: ['Nettavisen'],
    prefixes: ['Nettavisen -'],
  },
  {
    publisher: 'DN Media Group',
    countries: ['Norway'],
    exact: ['DN'],
    prefixes: ['DN -'],
  },
  {
    publisher: 'Finansavisen',
    countries: ['Norway'],
    exact: ['Finansavisen'],
    prefixes: ['Finansavisen -'],
  },
  {
    publisher: 'Dagbladet',
    countries: ['Norway'],
    exact: ['Dagbladet'],
    prefixes: ['Dagbladet -'],
  },
  {
    publisher: 'Dagsavisen',
    countries: ['Norway'],
    exact: ['Dagsavisen'],
    prefixes: ['Dagsavisen -'],
  },
  { publisher: 'TV4', countries: ['Sweden'], exact: ['TV4'], prefixes: ['TV4 -'] },
  {
    publisher: 'Dagens Nyheter',
    countries: ['Sweden'],
    exact: ['Dagens Nyheter'],
    prefixes: ['Dagens Nyheter ', 'Dagens Nyheter -'],
  },
  {
    publisher: 'Dagens Industri',
    countries: ['Sweden'],
    exact: ['Dagens Industri', 'Dagens Industri (Economy #1 Daily)'],
    prefixes: ['Dagens Industri ', 'Dagens Industri -'],
  },
  {
    publisher: 'SVT',
    countries: ['Sweden'],
    exact: ['SVT Nyheter', 'Sveriges Television', 'Svt'],
    prefixes: ['SVT ', 'SVT Lokal -'],
  },
  {
    publisher: 'Aftonbladet',
    countries: ['Sweden'],
    exact: ['Aftonbladet'],
    prefixes: ['Aftonbladet -'],
  },
  {
    publisher: 'Expressen',
    countries: ['Sweden'],
    exact: ['Expressen'],
    prefixes: ['Expressen -', 'GT -'],
  },
  {
    publisher: 'Svenska Dagbladet',
    countries: ['Sweden'],
    exact: ['Svenska Dagbladet'],
    prefixes: ['Svenska Dagbladet ', 'Svenska Dagbladet -'],
  },
  {
    publisher: 'Sveriges Radio',
    countries: ['Sweden'],
    prefixes: ['Sveriges Radio -', 'Radio Sweden -'],
  },
  {
    publisher: 'Cooperativa',
    countries: ['Chile'],
    prefixes: ['Cooperativa -'],
  },
  { publisher: '24Horas', countries: ['Chile'], prefixes: ['24Horas -', '24Horas'] },
  { publisher: 'Meganoticias', countries: ['Chile'], prefixes: ['Meganoticias'] },
  {
    publisher: 'La Tercera',
    countries: ['Chile'],
    prefixes: ['La Tercera -', 'Pulso (La Tercera'],
  },
  { publisher: 'Emol', countries: ['Chile'], prefixes: ['Emol -'] },
  { publisher: 'BioBioChile', countries: ['Chile'], prefixes: ['BioBioChile'] },
  {
    publisher: 'Ambito',
    countries: ['Argentina'],
    prefixes: ['Ámbito -', 'Ambito -'],
  },
  {
    publisher: 'Pagina/12',
    countries: ['Argentina'],
    prefixes: ['Página/12 -', 'Pagina/12 -'],
  },
  {
    publisher: 'Clarin',
    countries: ['Argentina'],
    prefixes: ['Clarín -', 'Clarin -'],
  },
  {
    publisher: 'La Nacion',
    countries: ['Argentina'],
    exact: ['La Nación', 'LA NACION'],
    prefixes: ['La Nación -', 'LA NACION -'],
  },
  { publisher: 'El Cronista', countries: ['Argentina'], prefixes: ['El Cronista -'] },
  { publisher: 'Infobae', countries: ['Argentina'], exact: ['Infobae'], prefixes: ['Infobae -'] },
  { publisher: 'TN', countries: ['Argentina'], exact: ['TN'] },
  {
    publisher: 'El Observador',
    countries: ['Uruguay'],
    exact: ['El Observador', 'El Observador Uruguay'],
    prefixes: ['El Observador -', 'El Observador Uruguay -'],
  },
  {
    publisher: 'El Pais Uruguay',
    countries: ['Uruguay'],
    exact: ['El País Uruguay'],
    prefixes: ['El País -', 'El Pais -', 'El País Uruguay -', 'El Pais Uruguay -'],
  },
  {
    publisher: 'Montevideo Portal',
    countries: ['Uruguay'],
    prefixes: ['Montevideo Portal -'],
  },
  {
    publisher: 'Subrayado',
    countries: ['Uruguay'],
    exact: ['Subrayado'],
    prefixes: ['Subrayado -', 'Teledoce -', 'Canal 10 Uruguay -'],
  },
  { publisher: 'Blick', countries: ['Switzerland'], prefixes: ['Blick', 'Blick Sport'] },
  { publisher: 'Blick FR', countries: ['Switzerland'], prefixes: ['Blick FR'] },
  { publisher: 'Le Matin', countries: ['Switzerland'], exact: ['Le Matin'], prefixes: ['Le Matin'] },
  { publisher: '20 Minuten', countries: ['Switzerland'], prefixes: ['20 Minuten'] },
  { publisher: '20 Minutes', countries: ['Switzerland'], prefixes: ['20 Minutes'] },
  {
    publisher: 'Tribune de Geneve',
    countries: ['Switzerland'],
    exact: ['Tribune de Geneve'],
    prefixes: ['Tribune de Geneve -'],
  },
  { publisher: 'NZZ', countries: ['Switzerland'], exact: ['NZZ'], prefixes: ['NZZ (', 'NZZ '] },
  { publisher: 'SRF', countries: ['Switzerland'], prefixes: ['SRF '] },
  { publisher: 'Swissinfo', countries: ['Switzerland'], prefixes: ['Swissinfo'] },
  { publisher: 'Le Temps', countries: ['Switzerland'], exact: ['Le Temps'], prefixes: ['Le Temps '] },
  { publisher: 'Ceska televize', countries: ['Czech Republic'], exact: ['ČT24'] },
  {
    publisher: 'Economia',
    countries: ['Czech Republic'],
    exact: ['Aktuálně.cz', 'Hospodarske noviny'],
    prefixes: ['Aktualne.cz', 'HN -'],
  },
  {
    publisher: 'Seznam.cz',
    countries: ['Czech Republic'],
    exact: ['Seznam Zprávy'],
    prefixes: ['Seznam Zpravy', 'Novinky.cz'],
  },
  {
    publisher: 'MAFRA',
    countries: ['Czech Republic'],
    exact: ['iDNES.cz', 'Lidovky.cz'],
    prefixes: ['iDNES.cz -'],
  },
  {
    publisher: 'Cesky rozhlas',
    countries: ['Czech Republic'],
    exact: ['iROZHLAS'],
    prefixes: ['iROZHLAS -'],
  },
  {
    publisher: 'FTV Prima',
    countries: ['Czech Republic'],
    exact: ['CNN Prima'],
  },
  {
    publisher: 'Czech News Center',
    countries: ['Czech Republic'],
    exact: ['E15', 'Reflex', 'Ahaonline.cz'],
    prefixes: ['Blesk -', 'iSport'],
  },
  {
    publisher: 'Denik',
    countries: ['Czech Republic'],
    exact: ['Deník', 'Denik'],
    prefixes: ['Denik -'],
  },
  {
    publisher: 'FTV Prima',
    countries: ['Czech Republic'],
    prefixes: ['Prima Zeny', 'Prima COOL', 'Prima Zoom'],
  },
  {
    publisher: 'Sport.cz',
    countries: ['Czech Republic'],
    exact: ['Sport.cz'],
    prefixes: ['Sport.cz -'],
  },
  {
    publisher: 'DR',
    countries: ['Denmark'],
    exact: ['DR Nyheder'],
    prefixes: ['DR '],
  },
  {
    publisher: 'Politiken',
    countries: ['Denmark'],
    exact: ['Politiken'],
    prefixes: ['Politiken -'],
  },
  {
    publisher: 'Borsen',
    countries: ['Denmark'],
    exact: ['Borsen'],
    prefixes: ['Borsen -', 'Finans.dk'],
  },
  {
    publisher: 'Berlingske Media',
    countries: ['Denmark'],
    exact: ['Berlingske', 'BT'],
  },
  {
    publisher: 'Information',
    countries: ['Denmark'],
    prefixes: ['Information'],
  },
  {
    publisher: 'Polsat News',
    countries: ['Poland'],
    exact: ['PolsatNews'],
    prefixes: ['PolsatNews '],
  },
  {
    publisher: 'TVN24',
    countries: ['Poland'],
    exact: ['TVN24'],
    prefixes: ['TVN24 ', 'TVN24 -'],
  },
  { publisher: 'RMF24', countries: ['Poland'], prefixes: ['RMF24'] },
  {
    publisher: 'Radio Zet',
    countries: ['Poland'],
    exact: ['RadioZet'],
    prefixes: ['RadioZet', 'Radio Zet'],
  },
  {
    publisher: 'Telewizja Polska',
    countries: ['Poland'],
    prefixes: ['TVP Info', 'TVP '],
  },
  {
    publisher: 'PAP',
    countries: ['Poland'],
    prefixes: ['PAP MediaRoom', 'Nauka w Polsce'],
  },
  {
    publisher: 'Agora',
    countries: ['Poland'],
    exact: ['Gazeta.pl (Top Portal News)'],
    prefixes: ['Wyborcza -', 'Gazeta.pl'],
  },
  { publisher: 'Business AM', countries: ['Belgium'], prefixes: ['Business AM'] },
  {
    publisher: 'VRT',
    countries: ['Belgium'],
    exact: ['VRT News'],
    prefixes: ['VRT News', 'VRT NWS'],
  },
  {
    publisher: 'La Libre',
    countries: ['Belgium'],
    exact: ['La Libre Belgique'],
    prefixes: ['La Libre Belgique'],
  },
  {
    publisher: 'RTBF',
    countries: ['Belgium'],
    exact: ['RTBF'],
    prefixes: ['RTBF'],
  },
  {
    publisher: 'Le Soir',
    countries: ['Belgium'],
    exact: ['Le Soir', 'Le Soir (main)'],
    prefixes: ['Le Soir -'],
  },
  {
    publisher: 'Mediahuis',
    countries: ['Belgium', 'Netherlands'],
    prefixes: ['De Standaard', 'Het Nieuwsblad', 'Nieuwsblad', 'Gazet van Antwerpen', 'Het Belang van Limburg'],
  },
  {
    publisher: 'DPG Media Belgium',
    countries: ['Belgium'],
    prefixes: ['De Morgen', 'HLN', '7sur7'],
  },
  {
    publisher: 'Sudinfo',
    countries: ['Belgium'],
    prefixes: ['Sudinfo', 'DHnet'],
  },
  {
    publisher: 'Omroep West',
    countries: ['Netherlands'],
    prefixes: ['Omroep West -'],
  },
  {
    publisher: 'RTV Utrecht',
    countries: ['Netherlands'],
    prefixes: ['RTV Utrecht -'],
  },
  {
    publisher: 'Omroep Gelderland',
    countries: ['Netherlands'],
    prefixes: ['GLD -', 'Omroep Gelderland'],
  },
  {
    publisher: 'RTV Oost',
    countries: ['Netherlands'],
    prefixes: ['Oost -', 'RTV Oost'],
  },
  {
    publisher: 'RTV Noord',
    countries: ['Netherlands'],
    prefixes: ['RTV Noord -'],
  },
  {
    publisher: 'Rijnmond',
    countries: ['Netherlands'],
    prefixes: ['Rijnmond -'],
  },
  {
    publisher: 'RTV Drenthe',
    countries: ['Netherlands'],
    prefixes: ['RTV Drenthe -'],
  },
  {
    publisher: 'L1',
    countries: ['Netherlands'],
    prefixes: ['L1 Nieuws -'],
  },
  {
    publisher: 'Omroep Zeeland',
    countries: ['Netherlands'],
    prefixes: ['Omroep Zeeland -'],
  },
  {
    publisher: 'Omroep Brabant',
    countries: ['Netherlands'],
    exact: ['Omroep Brabant'],
    prefixes: ['Omroep Brabant -'],
  },
  {
    publisher: 'Rappler',
    countries: ['Philippines'],
    exact: ['Rappler', 'Newsbreak'],
    prefixes: ['Rappler -', 'Newsbreak -'],
  },
  {
    publisher: 'Inquirer',
    countries: ['Philippines'],
    exact: ['Inquirer'],
    prefixes: [
      'Inquirer -',
      'Cebu Daily News -',
      'Bandera -',
      'POP Inquirer -',
      'Lifestyle Inquirer -',
      'USA Inquirer -',
    ],
  },
  {
    publisher: 'BusinessWorld',
    countries: ['Philippines'],
    exact: ['BusinessWorld'],
    prefixes: ['BusinessWorld -'],
  },
  {
    publisher: 'Philstar',
    countries: ['Philippines'],
    exact: ['Philippine Star'],
    prefixes: ['Philippine Star -'],
  },
  {
    publisher: 'GMA Network',
    countries: ['Philippines'],
    exact: ['GMA Network'],
  },
  {
    publisher: 'MindaNews',
    countries: ['Philippines'],
    exact: ['Mindanews'],
    prefixes: ['Mindanews -'],
  },
  {
    publisher: 'The Manila Times',
    countries: ['Philippines'],
    prefixes: ['The Manila Times -'],
  },
  {
    publisher: 'Manila Bulletin',
    countries: ['Philippines'],
    prefixes: ['Manila Bulletin -'],
  },
  {
    publisher: 'SunStar',
    countries: ['Philippines'],
    exact: ['SunStar'],
    prefixes: ['SunStar -'],
  },
  {
    publisher: 'InterAksyon',
    countries: ['Philippines'],
    exact: ['InterAksyon'],
    prefixes: ['InterAksyon -'],
  },
  {
    publisher: 'Daily Tribune',
    countries: ['Philippines'],
    exact: ['Daily Tribune'],
    prefixes: ['Daily Tribune -'],
  },
  {
    publisher: 'Globes',
    countries: ['Israel'],
    exact: ['Globes'],
    prefixes: ['Globes -'],
  },
  {
    publisher: 'Times of Israel',
    countries: ['Israel'],
    exact: ['Times of Israel'],
    prefixes: ['Times of Israel -'],
  },
  {
    publisher: 'Jerusalem Post',
    countries: ['Israel'],
    prefixes: ['Jerusalem Post -'],
  },
  {
    publisher: 'Ynet',
    countries: ['Israel'],
    exact: ['Ynet'],
    prefixes: ['Ynet -'],
  },
  {
    publisher: 'Haaretz',
    countries: ['Israel'],
    exact: ['Haaretz'],
    prefixes: ['Haaretz -'],
  },
  {
    publisher: 'TheMarker',
    countries: ['Israel'],
    exact: ['TheMarker'],
    prefixes: ['TheMarker -'],
  },
  {
    publisher: 'Walla',
    countries: ['Israel'],
    exact: ['Walla'],
    prefixes: ['Walla -'],
  },
  {
    publisher: 'mako',
    countries: ['Israel'],
    exact: ['mako'],
    prefixes: ['mako -'],
  },
  {
    publisher: 'Maariv',
    countries: ['Israel'],
    prefixes: ['Maariv -'],
  },
  {
    publisher: 'Israel Hayom',
    countries: ['Israel'],
    prefixes: ['Israel Hayom -'],
  },
];

function resolveRuleMatch(source: string, country: string, rule: PublisherRule): PublisherMatchType | null {
  const normalizedSource = normalize(source);
  if (rule.countries && rule.countries.length > 0 && !rule.countries.includes(country)) {
    return null;
  }
  if (rule.exact?.some((value) => normalize(value) === normalizedSource)) return 'exact';
  if (rule.prefixes?.some((value) => normalizedSource.startsWith(normalize(value)))) return 'prefix';
  if (rule.contains?.some((value) => normalizedSource.includes(normalize(value)))) return 'contains';
  return null;
}

function confidenceForMatch(rule: PublisherRule, matchType: PublisherMatchType): PublisherConfidence {
  if (rule.confidence) return rule.confidence;
  switch (matchType) {
    case 'exact':
      return 'high';
    case 'prefix':
      return 'medium';
    case 'contains':
    case 'fallback':
      return 'low';
  }
}

export function resolvePublisherInfo(source: string, country: string): ResolvedPublisher {
  for (const rule of PUBLISHER_RULES) {
    const matchType = resolveRuleMatch(source, country, rule);
    if (matchType) {
      return {
        publisher: rule.publisher,
        confidence: confidenceForMatch(rule, matchType),
        matchedBy: matchType,
      };
    }
  }

  return {
    publisher: buildDisplaySourceName(source),
    confidence: 'low',
    matchedBy: 'fallback',
  };
}

export function resolvePublisherName(source: string, country: string): string {
  return resolvePublisherInfo(source, country).publisher;
}
